drop table  if exists form_actra_contract;
CREATE TABLE `form_actra_contract` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `version` tinyint(4) NOT NULL DEFAULT '1',
  `Contract_Num` varchar(25) DEFAULT NULL,
  `Branch_Code` varchar(15) DEFAULT NULL,
  `Agency_Name` varchar(150) DEFAULT NULL,
  `Agency_Producer` varchar(150) DEFAULT NULL,
  `Agency_Address_Id` int(11) DEFAULT NULL,
  `Sponsor` varchar(150) DEFAULT NULL,
  `Product` varchar(150) DEFAULT NULL,
  `Prod_House_Name` varchar(150) DEFAULT NULL,
  `Prod_House_Address_Id` int(11) DEFAULT NULL,
  `Pay_Session_Fee` tinyint(1) DEFAULT '0',
  `Director_Name` varchar(150) DEFAULT NULL,
  `Loan_Out_Name` varchar(100) DEFAULT NULL,
  `Talent_Name` varchar(100) DEFAULT NULL,
  `Talent_Address_Id` int(11) DEFAULT NULL,
  `Talent_Email_Address` varchar(100) DEFAULT NULL,
  `Talent_Phone_Num` varchar(15) DEFAULT NULL,
  `Social_Insurance_Num` varchar(1000) DEFAULT NULL,
  `Gst_Hst` varchar(20) DEFAULT 'N/A',
  `Qst` varchar(20) DEFAULT 'N/A',
  `DOB` date DEFAULT NULL,
  `Talent_Agency_Name` varchar(150) DEFAULT NULL,
  `Performance_Category` varchar(15) DEFAULT NULL,
  `Full_Member_Num` varchar(15) DEFAULT NULL,
  `Apprentice_Num` varchar(45) DEFAULT NULL,
  `Work_Permit_Num` varchar(25) DEFAULT NULL,
  `National_Tv` varchar(15) DEFAULT NULL,
  `National_Radio` varchar(15) DEFAULT NULL,
  `National_Digital_Media_Video` varchar(15) DEFAULT NULL,
  `National_Digital_Media_Radio` varchar(15) DEFAULT NULL,
  `Tags_Tv` int(11) DEFAULT NULL,
  `Tags_Radio` int(11) DEFAULT NULL,
  `Tags_Digital_Media` int(11) DEFAULT NULL,
  `Regional_Changes_Tv` int(11) DEFAULT NULL,
  `Regional_Changes_Radio` int(11) DEFAULT NULL,
  `Regional_Changes_Digital_Media` int(11) DEFAULT NULL,
  `Psa_Tv` varchar(15) DEFAULT NULL,
  `Psa_Radio` varchar(15) DEFAULT NULL,
  `Psa_Digital_Media` varchar(15) DEFAULT NULL,
  `Demo_Tv` varchar(15) DEFAULT NULL,
  `Demo_Radio` varchar(15) DEFAULT NULL,
  `Demo_Presentation` varchar(15) DEFAULT NULL,
  `Demo_Infomercial` varchar(15) DEFAULT NULL,
  `Seasonal_Tv` varchar(15) DEFAULT NULL,
  `Seasonal_Radio` varchar(15) DEFAULT NULL,
  `Seasonal_Dealer` varchar(15) DEFAULT NULL,
  `Seasonal_Dealer_Tv` varchar(15) DEFAULT NULL,
  `Seasonal_Dealer_Radio` varchar(15) DEFAULT NULL,
  `Seasonal_Double_Shoot` varchar(15) DEFAULT NULL,
  `Seasonal_Joint_Promo` varchar(15) DEFAULT NULL,
  `Local_Regional_Category_Num` varchar(15) DEFAULT NULL,
  `Local_Regional_Tv` varchar(15) DEFAULT NULL,
  `Local_Regional_Radio` varchar(15) DEFAULT NULL,
  `Local_Regional_Digital_Media` varchar(15) DEFAULT NULL,
  `Local_Regional_Demo` varchar(15) DEFAULT NULL,
  `Local_Regional_Prepaid` varchar(15) DEFAULT NULL,
  `Local_Regional_Digital_Media_Broadcast` varchar(15) DEFAULT NULL,
  `Local_Regional_Broadcast_Digital_Media` varchar(15) DEFAULT NULL,
  `Local_Regional_Other` varchar(15) DEFAULT NULL,
  `Local_Regional_Pilot_Project` varchar(15) DEFAULT NULL,
  `Short_Life_Tv_7_Days` varchar(15) DEFAULT NULL,
  `Short_Life_Tv_14_Days` varchar(15) DEFAULT NULL,
  `Short_Life_Tv_31_Days` varchar(15) DEFAULT NULL,
  `Short_Life_Tv_45_Days` varchar(15) DEFAULT NULL,
  `Short_Life_Radio_7_Days` varchar(15) DEFAULT NULL,
  `Short_Life_Radio_14_Days` varchar(15) DEFAULT NULL,
  `Short_Life_Radio_31_Days` varchar(15) DEFAULT NULL,
  `Short_Life_Radio_45_Days` varchar(15) DEFAULT NULL,
  `Tv_Broadcast_Digital_Media` varchar(15) DEFAULT NULL,
  `Digital_Media_Broadcast_Tv` varchar(15) DEFAULT NULL,
  `Digital_Media_Other` varchar(15) DEFAULT NULL,
  `Radio_To_Digital_Media` varchar(15) DEFAULT NULL,
  `Pilot_Project` varchar(15) DEFAULT NULL,
  `Article_2403` varchar(15) DEFAULT NULL,
  `Article_2404` varchar(15) DEFAULT NULL,
  `Article_2405` varchar(15) DEFAULT NULL,
  `Article_2406` varchar(15) DEFAULT NULL,
  `Commercial_Name` varchar(250) DEFAULT NULL,
  `Docket` varchar(50) DEFAULT NULL,
  `Additional_Titles` varchar(250) DEFAULT NULL,
  `Session_Fees` varchar(100) DEFAULT NULL,
  `Residual_Fees` varchar(100) DEFAULT NULL,
  `Other_Fees` varchar(100) DEFAULT NULL,
  `Digital_Media_Fees` varchar(100) DEFAULT NULL,
  `Talent_Sign_Id` int(11) DEFAULT NULL,
  `Talent_Sign_Date` date DEFAULT NULL,
  `Producer_Sign_Id` int(11) DEFAULT NULL,
  `Producer_Sign_Date` date DEFAULT NULL,
  `Wardrobe_Call` decimal(4,2) DEFAULT NULL,
  `Wardrobe_Wrap` decimal(4,2) DEFAULT NULL,
  `Rehearsal_Call` decimal(4,2) DEFAULT NULL,
  `Rehearsal_Wrap` decimal(4,2) DEFAULT NULL,
  `Holding_Call` decimal(4,2) DEFAULT NULL,
  `Holding_Wrap` decimal(4,2) DEFAULT NULL,
  `NDM` tinyint(1) DEFAULT '0',
  `Talent_Initial_Agree_Id` int(11) DEFAULT NULL,
  `Talent_Initial_Disagree_Id` int(11) DEFAULT NULL,
  `Producer_Initial_Id` int(11) DEFAULT NULL,
  `Weekly_Timecard_Id` int(11) NOT NULL,
  `Created_By_id` int(11) NOT NULL,
  `Created_Date` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `Updated_By_Id` int(11) NOT NULL,
  `Updated_Date` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  KEY `Agency_Address_Id_idx` (`Agency_Address_Id`),
  KEY `Prod_House_Address_Id_idx` (`Prod_House_Address_Id`),
  KEY `Talent_Address_Id_idx` (`Talent_Address_Id`),
  KEY `Talent_Initial_Agree_Id_idx` (`Talent_Initial_Agree_Id`),
  KEY `Producer_Initial_Id_idx` (`Producer_Initial_Id`),
  KEY `Talent_Initial_Disagree_Id_idx` (`Talent_Initial_Disagree_Id`,`Talent_Initial_Agree_Id`),
  KEY `Updated_By_Id_idx` (`Updated_By_Id`),
  KEY `Created_By_Id_idx` (`Created_By_id`),
  CONSTRAINT `Agency_Address_Id` FOREIGN KEY (`Agency_Address_Id`) REFERENCES `address` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `Created_By_Id` FOREIGN KEY (`Created_By_id`) REFERENCES `user` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `Prod_House_Address_Id` FOREIGN KEY (`Prod_House_Address_Id`) REFERENCES `address` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `Producer_Initial_Id` FOREIGN KEY (`Producer_Initial_Id`) REFERENCES `time_card_event` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `Talent_Address_Id` FOREIGN KEY (`Talent_Address_Id`) REFERENCES `address` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `Talent_Initial_Agree_Id` FOREIGN KEY (`Talent_Initial_Agree_Id`) REFERENCES `time_card_event` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `Talent_Initial_Disagree_Id` FOREIGN KEY (`Talent_Initial_Disagree_Id`) REFERENCES `time_card_event` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `Updated_By_Id` FOREIGN KEY (`Updated_By_Id`) REFERENCES `user` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
