/*	File Name:	FormField.java */
package com.lightspeedeps.type;

import java.math.BigDecimal;
import java.util.Date;

/**
 * An enumeration used in the ?? to indicate which Lightspeed model field (e.g., User.firstName)
 * corresponds to a particular field in a form (e.g., a PDF).
 */
public enum FormFieldType {

	// I-9 and some shared fields

	DATE_DAY 				("Date - Day number", String.class),
	DATE_MONTH_SHORT		("Date - Month (mmm)", String.class),
	DATE_YEAR				("Date - Year (yyyy)", String.class),
	DATE_SHORT_YEAR			("Date - Year (yy)", String.class),
	TODAYS_DATE				("Today's Date - m/d/yyyy", Date.class),

	USER_FIRST_NAME 		("User First name", String.class),
	USER_MIDDLE_NAME 		("User Middle Name", String.class),
	USER_LAST_NAME 			("User Last name", String.class),
	FULL_NAME 				("User's Full name", String.class),
	USER_OR_LOAN_OUT_NAME	("User or Loan-out name", String.class),
	OTHER_NAME 				("Other Name", String.class),
	USER_DOB_MDY 			("User Date of birth as mm/dd/yyyy", Date.class),
	USER_DOB_YMD			("User Date of birth as yyyy/mm/dd", Date.class),
	USER_DOB_MONTH			("User Date of birth Month", Integer.class),
	USER_DOB_DAY			("User Date of birth Day", Integer.class),
	USER_DOB_YEAR			("User Date of birth Year", Integer.class),
	HOME_ADDR_STREET 		("Home address - Street address", String.class), // combines lines 1 & 2
	HOME_ADDR_LINE1 		("Home address - Line 1", String.class),
	HOME_ADDR_LINE2 		("Home address - Line 2", String.class),
	HOME_APT_NUMBER 		("Apt Number", String.class),
	HOME_ADDR_CITY_ONLY 	("Home address - City name", String.class),
	HOME_ADDR_STATE 		("Home address - State 			(2-letter code)", String.class),
	HOME_ADDR_ZIP 			("Home address - Zip code", String.class),
	HOME_ADDR_CITY_STATE_ZIP("Home addr as 'city, state zip'", String.class),
	HOME_ADDR_COUNTRY		("Home address - Country", String.class),
	HOME_ADDR_COUNTY		("Home address - County", String.class),
	HOME_ADDR_COMPLETE		("Home address all on one line", String.class),
	USER_EMAIL_ADDRESS 		("User Email address", String.class),
	USER_ACCOUNT 			("User Account", String.class),
	SOCIAL_SECURITY 		("Social Security", String.class),
	SOCIAL_SEC_PART_1 		("Social Security pt 1", String.class),
	SOCIAL_SEC_PART_2 		("Social Security pt 2", String.class),
	SOCIAL_SEC_PART_3 		("Social Security pt 3", String.class),
	SOCIAL_SEC_DIGIT_1 		("Social Security 1", String.class),
	SOCIAL_SEC_DIGIT_2 		("Social Security 2", String.class),
	SOCIAL_SEC_DIGIT_3 		("Social Security 3", String.class),
	SOCIAL_SEC_DIGIT_4 		("Social Security 4", String.class),
	SOCIAL_SEC_DIGIT_5 		("Social Security 5", String.class),
	SOCIAL_SEC_DIGIT_6 		("Social Security 6", String.class),
	SOCIAL_SEC_DIGIT_7 		("Social Security 7", String.class),
	SOCIAL_SEC_DIGIT_8 		("Social Security 8", String.class),
	SOCIAL_SEC_DIGIT_9 		("Social Security 9", String.class),
	USER_CELL_PHONE 		("Cell phone number", String.class),
	USER_HOME_PHONE 		("Home phone number", String.class),
	TELEPHONE_NUMBER 		("Telephone Number", String.class),
	AGENCY_NAME	 			("Agency Name", String.class), // for custom forms
	AGENCY_PHONE 			("Agency Telephone", String.class),
	// LS3825 New fields
	AGENCY_ADDR_STREET 		("Agency address - Street address", String.class), // combines lines 1 & 2
	AGENCY_ADDR_LINE1 		("Agency address - Line 1", String.class),
	AGENCY_ADDR_LINE2 		("Agency address - Line 2", String.class),
	AGENCY_APT_NUMBER 		("Agency Apt Number", String.class),
	AGENCY_ADDR_CITY_ONLY 	("Agency address - City name", String.class),
	AGENCY_ADDR_STATE 		("Agency address - State 			(2-letter code)", String.class),
	AGENCY_ADDR_ZIP 		("Agency address - Zip code", String.class),
	AGENCY_ADDR_CITY_STATE_ZIP("Agency addr as 'city, state zip'", String.class),
	AGENCY_ADDR_COUNTRY		("Agency address - Country", String.class),
	MAILING_ADDR_STREET 	("Mailing address - Street address", String.class), // combines lines 1 & 2
	MAILING_ADDR_LINE1 		("Mailing address - Line 1", String.class),
	MAILING_ADDR_LINE2 		("Mailing address - Line 2", String.class),
	MAILING_APT_NUMBER 		("Mailing Apt Number", String.class),
	MAILING_ADDR_CITY_ONLY 	("Mailing address - City name", String.class),
	MAILING_ADDR_STATE 		("Mailing address - State 			(2-letter code)", String.class),
	MAILING_ADDR_ZIP 		("Mailing address - Zip code", String.class),
	MAILING_ADDR_CITY_STATE_ZIP("Mailing addr as 'city, state zip'", String.class),
	MAILING_ADDR_COUNTY		("Mailing address - County", String.class),
	MAILING_ADDR_COUNTRY	("Mailing address - Country", String.class),
	MAILING_ADDR_COMPLETE	("Mailing address all on one line", String.class),
	// LS-4242
	NONRESIDENT_ADDR_STREET 	("Non-Resident address - Street address", String.class), // combines lines 1 & 2
	NONRESIDENT_ADDR_LINE1 		("Non-Resident address - Line 1", String.class),
	NONRESIDENT_ADDR_LINE2 		("Non-Resident address - Line 2", String.class),
	NONRESIDENT_APT_NUMBER 		("Non-Resident Apt Number", String.class),
	NONRESIDENT_ADDR_CITY_ONLY 	("Non-Resident address - City name", String.class),
	NONRESIDENT_ADDR_STATE 		("Non-Resident address - State 			(2-letter code)", String.class),
	NONRESIDENT_ADDR_ZIP 		("Non-Resident address - Zip code", String.class),
	NONRESIDENT_ADDR_CITY_STATE_ZIP("Non-Resident addr as 'city, state zip'", String.class),
	NONRESIDENT_ADDR_COUNTY		("Non-Resident address - County", String.class),
	NONRESIDENT_ADDR_COUNTRY	("Non-Resident address - Country", String.class),
	NONRESIDENT_ADDR_COMPLETE	("Non-Resident address all on one line", String.class),

	// I-9 Fields (mostly)
	// LS-1859: some of these enum values are generated from the Form I-9 xhtml 'id' values!
	// Do not change names without checking this.  See FormI9Bean.saveChangeEvent().
	CITIZENSHIP_STATUS 		("Citizenship Status", String.class),
	CITIZENSHIP_STATUS_C 	("Citizenship Status Citizen", String.class),
	CITIZENSHIP_STATUS_N 	("Citizenship Status Non-Citizen", String.class),
	CITIZENSHIP_STATUS_P 	("Citizenship Status Permanent Resident", String.class),
	CITIZENSHIP_STATUS_A	("Citizenship Status Alien", String.class),
	CITIZENSHIP_BOX_A 		("Citizenship Box A", String.class),
	CITIZENSHIP_BOX_B 		("Citizenship Box B", String.class),
	CITIZENSHIP_BOX_C 		("Citizenship Box C", String.class),
	CITIZENSHIP_BOX_D 		("Citizenship Box D", String.class),
	ALIEN_REG_NUMBER1 		("Alien Reg Number1", String.class),
	ALIEN_USCIS1 		  	("Alien Uscis1", String.class),
	ALIEN_REG_NUMBER2 		("Alien Reg Number2", String.class),
	ALIEN_USCIS2  			("Alien Uscis2", String.class),
	WORK_AUTH_EXPIRATION_DATE("Work Auth Expiration Date", Date.class),
	FORM_I94_ADMISSION_NO 	("Form I9 Admission No", String.class),
	FOREIGN_PASSPORT_NO 	("Foreign Passport No", String.class),
	FOREIGN_COUNTRY_OF_ISSUANCE	("Foreign Country Of Issuance", String.class),
	EMPLOYEE_SIGNATURE_NAME ("Employee Signature", String.class),
	EMPLOYEE_SIGNATURE_DATE ("Employee Signature Date", Date.class),
	EMPLOYEE_2_SIGNATURE_NAME ("Employee Second Signature", String.class),
	EMPLOYEE_2_SIGNATURE_DATE ("Employee Second Signature Date", Date.class),
	PREP_SIGNATURE_NAME 	("Preparer Signature", String.class),
	PREP_SIGNATURE_DATE 	("Preparer Signature Date", Date.class),
	PREPARER_NOT_USED 		("Preparer Not Used", String.class),
	PREPARER_USED 			("Preparer Used", String.class),
	NUMBER_OF_PREPARERS 	("Number Of Preparers", String.class),
	PREPARER_LAST_NAME 		("Preparer Last Name", String.class),
	PREPARER_FIRST_NAME 	("Preparer First Name", String.class),
	PREP_ADDR_STREET 		("Preparer address - Street address", String.class),
	PREP_ADDR_CITY_ONLY 	("Preparer address - City name", String.class),
	PREP_ADDR_STATE 		("Preparer address - State 			(2-letter code)", String.class),
	PREP_ADDR_ZIP 			("Preparer address - Zip code", String.class),
	PREP_ADDR_CITY_STATE_ZIP("Preparer addr as 'city, state zip'", String.class),
	SEC2_LAST_NAME 			("Sec2 Last Name", String.class),
	SEC2_FIRST_NAME 		("Sec2 First Name", String.class),
	SEC2_MIDDLE_INITIAL 	("Sec2 Middle Initial", String.class),
	SEC2_CITIZENSHIP_STATUS ("Sec2 Citizenship Status", String.class),
	ADDITIONAL_INFORMATION	("Additional Information", String.class),
	A1_DOC_TITLE 			("A1 Doc Title", String.class),
	A1_ISSUING_AUTH 		("A1 Issuing Auth", String.class),
	A1_DOC_NUMBER 			("A1 Doc Number", String.class),
	A1_DOC_EXPIRATION 		("A1 Doc Expiration", Date.class),
	A2_DOC_TITLE 			("A2 Doc Title", String.class),
	A2_ISSUING_AUTH 		("A2 Issuing Auth", String.class),
	A2_DOC_NUMBER 			("A2 Doc Number", String.class),
	A2_DOC_EXPIRATION 		("A2 Doc Expiration", Date.class),
	A3_DOC_TITLE 			("A3 Doc Title", String.class),
	A3_ISSUING_AUTH 		("A3 Issuing Auth", String.class),
	A3_DOC_NUMBER 			("A3 Doc Number", String.class),
	A3_DOC_EXPIRATION 		("A3 Doc Expiration", Date.class),
	B_DOC_TITLE 			("B Doc Title", String.class),
	B_ISSUING_AUTH 			("B Issuing Auth", String.class),
	B_DOC_NUMBER 			("B Doc Number", String.class),
	B_DOC_EXPIRATION 		("B Doc Expiration", Date.class),
	C_DOC_TITLE 			("C Doc Title", String.class),
	C_ISSUING_AUTH 			("C Issuing Auth", String.class),
	C_DOC_NUMBER 			("C Doc Number", String.class),
	C_DOC_EXPIRATION 		("C Doc Expiration", Date.class),
	FIRST_DAY_OF_EMPLOYMENT ("First Day Of Employment", Date.class),
	EMP_LAST_NAME 			("Employer Last Name", String.class),
	EMP_FIRST_NAME 			("Employer First Name", String.class),
	EMP_TITLE 				("Employer Title", String.class),
	EMP_BUSINESS_NAME 		("Employer Business Name", String.class),
	EMP_ADDR_STREET 		("Employer address - Street address", String.class),
	EMP_ADDR_CITY 			("Employer address - City name", String.class), // Used in I9 audit trail (DocChangeEvent). LS-1859
	EMP_ADDR_CITY_ONLY 		("Employer address - City name", String.class), // Use this one for XFDF fields
	EMP_ADDR_STATE 			("Employer address - State 			(2-letter code)", String.class),
	EMP_ADDR_ZIP 			("Employer address - Zip code", String.class),
	EMP_ADDR_CITY_STATE_ZIP ("Employer addr as 'city, state zip'", String.class),
	EMP_SIGNATURE_NAME 		("Employer Signature", String.class),
	EMP_SIGNATURE_DATE 		("Employer Signature Date", Date.class),
	SEC3_NEW_LAST_NAME 		("Sec3 New Last Name", String.class),
	SEC3_NEW_FIRST_NAME 	("Sec3 New First Name", String.class),
	SEC3_NEW_MIDDLE_INITIAL ("Sec3 New Middle Initial", String.class),
	SEC3_LAST_NAME 			("Sec3 Last Name", String.class),
	SEC3_FIRST_NAME 		("Sec3 First Name", String.class),
	SEC3_MIDDLE_INITIAL 	("Sec3 Middle Initial", String.class),
	SEC3_REHIRE_DATE 		("Sec3 Rehire Date", Date.class),
	SEC3_DOC_TITLE 			("Sec3 Doc Title", String.class),
	SEC3_DOC_NUMBER 		("Sec3 Doc Number", String.class),
	SEC3_DOC_EXPIRATION 	("Sec3 Doc Expiration", Date.class),
	SEC3_EMP_NAME 			("Sec3 Employer Name", String.class),
	SEC3_SIGNATURE_NAME 	("Sec3 Signature", String.class),
	SEC3_SIGNATURE_DATE 	("Sec3 Signature Date", Date.class),

	// W-4 Fields; when used in a custom form, the
	// values will be taken from the User defaults ("My Account")
	W4_PERSONAL_SELF		("Personal Self", Integer.class),
	W4_PERSONAL_MARRIED		("Personal Married", Integer.class),
	W4_PERSONAL_SPOUSE		("Personal Spouse", Integer.class),
	W4_PERSONAL_DEPENDENTS	("Personal Dependents", Integer.class),
	W4_PERSONAL_HOH			("Personal HoH", Integer.class),
	W4_PERSONAL_CARE		("Personal Care", Integer.class),
	W4_PERSONAL_CHILD		("Personal Child", Integer.class),
	W4_PERSONAL_SUM			("Personal Sum", Integer.class),
	W4_MARITAL_CHOICE		("Marital", String.class),
	W4_MARITAL_SINGLE		("Marital: Single", String.class),
	W4_MARITAL_MARRIED		("Marital: Married", String.class),
	W4_MARITAL_MARR_SEP		("Marital: Married filing separately", String.class),
	W4_MARITAL_DISABLED		("Marital: Certified Disabled", String.class),
	W4_MARITAL_MILITARY_SPOUSE	("Marital: Military Spouse", String.class),
	// LS-4234 Marital Statuses for PR
	W4_MARITAL_NONE_SINGLE	("Marital: Single but with less withhold", String.class),
	W4_MARITAL_NNE_MARRIED	("Marital: Married but with less withhold", String.class),
	W4_MARITAL_OTHER		("Marital: W/H at Higher Rate", String.class),
	W4_NAME_DIFFERS			("Name Differs", String.class),
	W4_ALLOWANCES			("Allowances", Integer.class),
	W4_ADDTL_AMOUNT			("Addtl Amount", Integer.class),
	W4_EXEMPT				("Exempt", String.class),
	W4_EMPLOYER_NAME		("Employer Name", String.class),
	W4_EMPLOYER_ADDRESS		("Employer Address", String.class),
	W4_OFFICE_CODE			("Office Code", String.class),
	W4_EMP_ID_NUMBER		("Employer Id Number", Integer.class),
	W4_DEDUCTIONS			("Deductions", Integer.class),
	W4_AUTOMATIC			("Automatic", Integer.class),
	W4_NET_DEDUCTIONS		("Net Deductions", Integer.class),
	W4_ADJUSTMENTS			("Adjustments", Integer.class),
	W4_SUM_DEDUCTIONS		("Sum Deductions", Integer.class),
	W4_EST_NON_WAGE			("Est Non Wage", Integer.class),
	W4_SUBTRACT_NON_WAGE	("Subtract Non Wage", Integer.class),
	W4_DIVIDED_BY			("Divided By", Integer.class),
	W4_TOTAL_DEDUCTS		("Total Deducts", Integer.class),
	W4_TABLE1_LOOKUP_1		("Table1 Lookup", Integer.class),
	W4_TABLE1_LOOKUP_2		("Table1 Lookup #2 (line 4)", Integer.class),
	W4_COMPARE_1_AND_2		("Compare 1 and 2", Integer.class),
	W4_DIFF_EXEMPTIONS		("Difference of Exemptions", Integer.class),
	W4_TABLE2_LOOKUP		("Table2 Lookup", Integer.class),
	W4_EST_EXEMPTIONS_1		("Est Exemptions", Integer.class),
	W4_EST_EXEMPTIONS_2		("Est Exemptions #2 (line 5)", Integer.class),
	W4_ADDTL_WITHHOLDING	("addtlWithholding", Integer.class),
	W4_ADDTL_PER_PAY_PERIOD	("Addtl Per Pay Period", Integer.class),
	// LS-3248 W4 2020
	W4_MULTIPLE_JOBS		("Worked multiple jobs", Integer.class),
	W4_NUM_CHILDREN_AMT		("Total dollar amount for children", Boolean.class),
	W4_NUM_DEPENDENTS_AMT	("Total dollar amount for dependencies", Integer.class),
	W4_TOTAL_DEPENDENTS_AMT	("Sum of children and dependencies amounts", Integer.class),
	W4_OTHER_INCOME_WITHHOLDING_AMT	("Withholdings for other income", Integer.class),
	W4_DEDUCTIONS_WITHHOLDINGS_AMT	("Withholdings for deductions", Integer.class),
	W4_EXTRA_WITHHOLDINGS_AMT	("Extra Withholdings", Integer.class),
	// LS-3247 W4 2020 Worksheet fields
	W4_NUM_PAY_PERIODS		("Number of pay periods for Multiple Jobs calculations", Integer.class),
	W4_TWO_JOBS_TOTAL_TAXABLE_WAGES	("Two jobs total taxable wages", Integer.class),
	W4_THREE_JOBS_HIGH_TAXABLE_WAGES ("Three jobs high taxable wages", Integer.class),
	W4_THREE_JOBS_HIGH_LOW_TAXABLE_WAGES ("Three jobs high/low taxable wages", Integer.class),
	W4_THREE_JOBS_TOTAL_TAXABLE_WAGES ("Three jobs total", Integer.class),
	W4_MULTIPLE_JOBS_TOTAL	("Total amount for the mulitple jobs section", Integer.class),
	W4_EST_ITEMIZED_DEDUCTIONS	("Estimated itemized deductions", Integer.class),
	W4_FILING_STATUS_AMT ("Filing status deduction", Integer.class),
	W4_SUB_TOTAL_DEDUCTIONS ("Sub-total of deductions section", Integer.class),
	W4_OTHER_DEDUCTIONS_AMT	("Other deductions amount", Integer.class),
	W4_DEDUCTIONS_TOTAL_AMT ("Total amount for Deductions section", Integer.class),
	// LS-3244
	W4_FIRST_DATE_EMPLOYMENT ("Employee's start date from Payroll Start Form", Date.class),
	W4_COUNTRY_NAME          ("Country Name", String.class),
	W4_COMPLETE_ADDRESS      ("Complete Address", String.class),
	// LS-4234
	W4_COMPLETE_MAILING_ADDRESS    ("Complete Mailing Address", String.class),
	W4_SPOUSE_SOCIAL_SECURITY		("Spouse's Social Security number", String.class),
	W4_FULL_SPOUSE_NAME		("Spouse's Social Security number", String.class),
	W4_TOTAL_ALLOWANCES_AMT	("Total oa all allowances", Integer.class),
	// LS-4099
	W4_TOTAL_EXEMPTIONS		("Total number of exemptions", Integer.class),
	// LS-4242
	W4_NONRESIDENT_NAME		("Non-resident name", String.class),
	W4_NONRESIDENT_SOCIAL_SECURITY 	("Non-resident Social Security", String.class),
	W4_LEGAL_STATE_OF_RESIDENCE	("Legal state of resdence", String.class),
	W4_LESS_WITHHOLDINGS		("Less withholdings", Boolean.class),
	
	//  * * * * Individual state W4 field types follow (ordered by 2-letter state code) * * * *
	// AL-W4
	AL_MARITAL_STATUS_CODE_S_MS	("Marital Status Code for filing Single or Married Filling Separately", String.class),
	AL_MARITAL_STATUS_CODE_M_H	("Marital Status Code for filing Married Single/Head of Household", String.class),
	
	// AR-W4
	AR_LOW_INCOME_TAX	            ("Qualify for the low-income tax rates", Boolean.class),
	AR_EXEMPT_STATUS1	            ("First Exempt Status", Boolean.class),
	AR_EXEMPT_STATUS2	            ("Second Exempt Status", Boolean.class),
	AR_EXEMPT_STATUS3	            ("Third Exempt Status", Boolean.class),
	
	// AZ-W4 Fields (Alabama)
	A4_CHECK1_WITHHLD				("Checkbox1Withhold", String.class), // TODO - change so it's not a prefix of others
	A4_CHECK1_WITHHOLD_08			("Checkbox1Withhold08", String.class),
	A4_CHECK1_WITHHOLD_13			("Checkbox1Withhold13", String.class),
	A4_CHECK1_WITHHOLD_18			("Checkbox1Withhold18", String.class),
	A4_CHECK1_WITHHOLD_36			("Checkbox1Withhold36", String.class),
	A4_CHECK1_WITHHOLD_42			("Checkbox1Withhold42", String.class),
	A4_CHECK1_WITHHOLD_51			("Checkbox1Withhold51", String.class),
	A4_CHECK1_WITHHOLD_27			("Checkbox1Withhold27", String.class),
	A4_CHECK_EXTRA_AMOUNT			("CheckboxExtraAmount", String.class),
	A4_EXTRA_AMOUNT					("ExtraAmount", Integer.class),
	A4_CHECK2_ZERO_WITHHOLD			("Checkbox2-ZeroWithhold", String.class),

	// CA W4 fields
	CAW4_EMP_TAX_ACCOUNT_NUMBER		("Employer Tax account number", Integer.class),
	CAW4_CERTIFY_FOR_PENALTY		("Certify For panalty", Boolean.class),
	CAW4_AMOUNT_TYPE				("Amount Type Dollar or Percent", String.class),

	// CT W4 fields
	CTW4_WITHHOLDING_CODE               ("Withholding Code", String.class),
	CTW4_MSRRA_EXEMPTION                ("If Employee claims for MSSRA Exemption", Boolean.class),
	CTW4_DOMICILE_STATE                 ("State of legal Domicile", String.class),
	
	// DC W4 fields
	DC_W4_TAXPAYER_ID_NUMBER		    ("Taxpayer Identification Number", String.class),
	DC_W4_TOTAL_SECTION_A           	("Total from Section A", Integer.class),
	DC_W4_TOTAL_SECTION_B           	("Total from Section B", Integer.class),
	DC_W4_TOTAL_WITHHOLD_ALLOWANCE    	("Withholding allowances Section Total", String.class),
	DC_W4_DISTRICT_COLUMBIA          	("District of Columbia", Boolean.class),
	DC_W4_FULLTIME_STUDENT          	("Fulltime student", Boolean.class),
	DC_ZIPCODE 						    ("ZipCode", String.class),
	DC_EXT_ZIPCODE 						("Extended ZipCode", String.class),
	
	// GA-W4 Fields (Georgia)
	G4_MARITAL_SINGLE					("Marital Status-Single", Integer.class),
	G4_MARITAL_MARRIED_BOTH_WORKING		("Marital Status-Married Both Working", Integer.class),
	G4_MARITAL_MARRIED_ONE_WORKING		("Marital Status-Married One Working", Integer.class),
	G4_MARITAL_MARRIED_FILING_SEPARATE  ("Marital Status-Married Filling Separately", Integer.class),
	G4_MARITAL_HEAD_OF_HOUSEHOLD		("Marital Status-Head of the Household", Integer.class),
	G4_MARITAL_DEPENDANT_ALLOWANCES		("Marital Status-Dependant Allowances", Integer.class),
	G4_MARITAL_ADDITIONAL_ALLOWANCES	("Marital Status-Additional Allowances", Integer.class),
	G4_MARITAL_ADDITIONAL_WITHHOLDINGS	("Marital Status-Additional Withholdings", Integer.class),
	G4_WORKSHEET_YOURSELF_OVER65		("Worksheet Yourself Over 65 Checkbox", String.class),
	G4_WORKSHEET_YOURSELF_BLIND			("Worksheet Yourself Blind Checkbox", String.class),
	G4_WORKSHEET_SPOUSE_OVER65			("Worksheet Spouse Over 65 Checkbox", String.class),
	G4_WORKSHEET_SPOUSE_BLIND			("Worksheet Spouse Blind Checkbox", String.class),
	G4_WORKSHEET_NUMBER_OF_BOXES		("Worksheet Number of  Selected Checked Boxes", String.class),
	G4_WORKSHEET_STANDARD_DEDUCTION		("Worksheet Standard Deductions", String.class),
	G4_WORKSHEET_FEDERAL_DEDUCTIONS		("Worksheet Federal Deductions", String.class),
	G4_WORKSHEET_GEORGIA_DEDUCTIONS		("Worksheet Georgia Deductions", String.class),
	G4_WORKSHEET_B_A					("Worksheet Line B - Line A", String.class),
	G4_WORKSHEET_ALLOWABLE_DEDUCTIONS	("Worksheet Allowable Deductions", String.class),
	G4_WORKSHEET_1_2C_2D				("Worksheet Line1+2C+2D", String.class),
	G4_WORKSHEET_TAXABLE_INCOME			("Worksheet Taxable Income", String.class),
	G4_WORKSHEET_F_E					("Worksheet Line F- Line E", String.class),
	G4_WORKSHEET_G_3000					("Worksheet Line G/3000", String.class),
	G4_MARITAL_STATUS_LETTER			("Marital Status Letter", String.class),
	G4_TOTAL_ALLOWANCES					("Total Allowances", String.class),
	G4_EXEMPT_CHECK						("Exempt Checkbox", String.class),
	G4_EXEMPT_EMPSTATE					("Exempt Employee State", String.class),
	G4_EXEMPT_SPOUSESTATE				("Exempt Spouse State", String.class),
	G4_EXEMPT_SAME_STATES_CHECK			("Exempt Same State Checkbox", String.class),
	G4_EMPLOYER_NAME_ADDR				("Employer's Name and Address", String.class),
	G4_EMP_ID_NUMBER					("Employer's FEIN number", String.class),
	G4_EMPLOYERS_WH						("Employer's WH #", String.class),
	
	//IAW4 fields
	IA_W4_EFFECTIVE_YEAR 				("Effective Year", Integer.class),
	IA_W4_EXEMPT_LOW_INCOME			    ("Claim if Exemptions Low Income", Boolean.class),
	IA_W4_PERSONAL_ALLOWANCES			("Personal Allowances", Integer.class),
	IA_W4_DEPENDENTS_ALLOWANCES			("Dependents Allowances", Integer.class),
	IA_W4_DEDUCTION_ALLOWANCE			("Deductions Allowances", Integer.class),
	IA_W4_ADJUSTMENT_ALLOWANCES			("Adjustment Allowances", Integer.class),
	IA_W4_CHILD_DEPENDENT_ALLOWANCES	("Child Dependent Allowances", Integer.class),

	// IL-W4 Fields (Illinois)
	ILW4_LINE_1							("Total number of boxes checked", String.class),
	ILW4_LINE_2							("Number of Dependents", String.class),
	ILW4_LINE_3							("Step 1 Line1 + Line2", String.class),
	ILW4_LINE_4							("Total number of Basic Personal Allowances", Integer.class),
	ILW4_LINE_5							("Total number of boxes checked step 2", String.class),
	ILW4_LINE_6							("Deductions and Adjustments", Integer.class),
	ILW4_LINE_7							("Step 2 Line 6/1000", Integer.class),
	ILW4_LINE_8							("Step 2 Line5 + Line7", Integer.class),
	ILW4_LINE_9							("Total number of Additional Allowances", Integer.class),

	//IN-W4 fields
	INW4_COUNTY_OF_RESIDENCE        ("Indian county of residence as of January 1", Integer.class),
	INW4_COUNTY_OF_PRINCIPAL        ("Indian county of principal as of January 1", Integer.class),
	INW4_OLDER                      ("Employe is 65 or older", Boolean.class),
	INW4_SPOUSE_OLDER               ("Employee's spouse is 65 or older", Boolean.class),
	INW4_TOTAL_CHECKED_BOXES        ("Total number of checked boxes" ,Integer.class),
	INW4_TOTAL_EXEMPTIONS           ("Employee's total exemptions", Integer.class),
	INW4_ADD_STATE_WITHHOLD         ("Amount of additional state withholding each pay period", Integer.class),
	INW4_ADD_COUNTY_WITHHOLD        ("Amount of additional county withholding each pay period", Integer.class),
	
	//KS
	KS_W4_UNION_COUPLE_JOINT        ("Couple joint", Boolean.class),
	
	//KY-W4
	KY_W4_CHECK_BOX_1               ("Check Box Section 1", String.class),
	KY_W4_CHECK_BOX_2               ("Check Box Section 2", String.class),
	KY_W4_CHECK_BOX_3               ("Check Box Section 3", String.class),
	KY_W4_CHECK_BOX_4               ("Check Box Section 4", String.class),
	KY_W4_CHECK_BOX_5               ("Check Box Section 5", String.class),
	KY_W4_CHECK_BOX_6               ("Check Box Section 6", String.class),
	KY_W4_CHECK_BOX_7               ("Check Box Section 7", String.class),
	KY_W4_CHECK_BOX_8               ("Check Box Section 8", String.class),
	KY_W4_CHECK_BOX_9               ("Check Box Section 9", String.class),
	KY_W4_CHECK_BOX_10              ("Check Box Section 10", String.class),
	KY_W4_CHECK_BOX_11              ("Check Box Section 11", String.class),
	KY_W4_CHECK_BOX_12              ("Check Box Section 12", String.class),
	KY_W4_ILLINIOS_CHECK_BOX        ("Illinios", String.class),
	KY_W4_INDIANA_CHECK_BOX         ("Indiana", String.class),
	KY_W4_MICHINGAN_CHECK_BOX       ("Michingan", String.class),
	KY_W4_WEST_VIRGIN_CHK_BOX       ("West Virgin", String.class),
    KY_W4_WISCONSIN_CHK_BOX         ("Wisconsin", String.class),
	KY_W4_VIRGINIA_CHK_BOX          ("Virginia", String.class),
	KY_W4_OHIO_CHK_BOX              ("Ohio", String.class),

	// LA-W4 Fields (Louisiana)
	L4_BLOCK_A							("Block A", String.class),
	L4_BLOCK_B							("Block B", String.class),
	L4_MARITAL_SINGLE					("Single", String.class),
	L4_MARITAL_MARRIED					("Married", String.class),
	L4_MARITAL_NO_EXEMPTION				("No Exemptions or Dependents Claimed", String.class),
	L4_EMP_ACCT_NUM						("Employer Account Number", String.class),
	L4_EMP_NAME_ADDRESS					("Employer Name and Address", String.class),
	L4_WITHHELD_ADJUSTMENT				("Withheld Adjustments", Integer.class),

	// MA-W4 fields
	MAW4_PERSONAL_EXEMPTIONS		("Employee's Personal exemptions", Integer.class),
	MAW4_SPOUSE_EXEMPTIONS			("Employee is Married and exemptions for spouse is allowed", Integer.class),
	MAW4_QUALIFIED_DEPENDENTS		("The number of qualified dependent", Integer.class),
	MAW4_CLAIMED_EXEMPTIONS			("The number of exemptions which Employee has claimed", Integer.class),
	MAW4_HEAD_OF_HOUSEHOLD			("Check employee will file as head of household", Boolean.class),
	MAW4_BLIND						("Check employee is blind", Boolean.class),
	MAW4_SPOUSE_BLIND				("Check if employee's spouse is blind and not subject to withholding", Boolean.class),
	MAW4_FULLTIME_STUDENT			("Check if employee is fulltime student and engaged in seasonal", Boolean.class),
	
	// MD-W4 fields
	MDW4_DC_EXEMPTION				("DC is the domiciled state", Boolean.class),
	MDW4_VA_EXEMPTION				("VA is the domiciled state", Boolean.class),
	MDW4_WV_EXEMPTION				("WV is the domiciled state", Boolean.class),
	MDW4_DID_NOT_OWE_TAX			("Did not owe MD tax", Boolean.class),
	MDW4_DO_NOT_EXPECT_OWE_TAX		("Do not expect to owe MD tax", Boolean.class),
	MDW4_1EXEMPT_STATUS				("Exempt Status", String.class),
	MDW4_2EXEMPT_STATUS				("Exempt Status", String.class),
	MDW4_3EXEMPT_STATUS				("Exempt Status", String.class),
	MDW4_4EXEMPT_STATUS				("Exempt Status", String.class),
	MDW4_5EXEMPT_STATUS				("Exempt Status", String.class),
	MDW4_6EXEMPT_STATUS				("Exempt Status", String.class),
	MDW4_RESIDENT_STATE				("Resident State", String.class),
	MDW4_YEAR_EFFECTIVE				("Year that is form applies to", String.class),
	
	// ME-W4 fields
	ME_W4_FEDERAL_FORM			    ("Federal form", Boolean.class),
	ME_W4_TAX_LIABIITY			    ("Tax liability", Boolean.class),
	ME_W4_PERODIC_RETIREMENT		("Perodic Retirement", Boolean.class),
	ME_W4_MILITARY_RESIDENCY		("Military Residency", Boolean.class),
	ME_W4_EXMPT			            ("Federal form", Boolean.class),
	ME_W4_SINGLE                    ("Single", Boolean.class),
	ME_W4_MARRIED                   ("Married", Boolean.class),
	ME_W4_MARIED_WITHHOLD           ("Married Withhold", Boolean.class),
	
	// MI-W4 fields
	MIW4_LICENCE_NO                 ("Driver's Licence Numver or state ID", String.class),
	MIW4_EMPLOYER_YES               ("Is Employer Yes" , Boolean.class ),
	MIW4_EMPLOYER_NO                ("Is Employer No", Boolean.class),
	MIW4_HIRE_DATE                  ("Date of Hire", Date.class),
	MIW4_CLAIMING                   ("Number of personal and dependent exemptions are claiming", Integer.class),
	MIW4_DEDUCTION_AMOUNT           ("Additional amount deducted from each pay", Integer.class),
	MIW4_8A                         ("If tax liability is not expected", Boolean.class),
	MIW4_8B                         ("If wages are exempt from withholding", Boolean.class),
	MIW4_8C                         ("If permanent home is located in given renaissance zone", Boolean.class),
	MIW4_EXPLAIN                    ("Explain", String.class),
	MIW4_RENAISSANCE_ZONE           ("Renaissance Zone", String.class),
	MIW4_DOB                        ("Date of Birth", String.class),
	
	//MN Print
	MN_W4_SINGLE                    ("Single", String.class),
	MN_W4_MARRIED                   ("Married", String.class),
	MN_W4_MARIED_WITHHOLD           ("Married Withhold", String.class),
	MN_W4_ALLOWNCE                  ("Allowance", String.class),
	MN_W4_ALLOW_SECTION_A           ("Allowance Section A", Integer.class),
	MN_W4_ALLOW_SECTION_B           ("Allowance Section B", Integer.class),
	MN_W4_ALLOW_SECTION_C           ("Allowance Section C", Integer.class),
	MN_W4_ALLOW_SECTION_D           ("Allowance Section D", Integer.class),
	MN_W4_ALLOW_SECTION_E           ("Allowance Section E", Integer.class),
	MN_W4_ALLOW_SECTION_F           ("Allowance Section F", Integer.class),
	MN_W4_WITHHOLDING               ("Withholding", Integer.class),
	MN_W4_WITHHOLD_SECTION_A        ("Withholding Section A", String.class),
	MN_W4_WITHHOLD_SECTION_B        ("Withholding Section B", String.class),
	MN_W4_WITHHOLD_SECTION_C        ("Withholding Section C", String.class),
	MN_W4_WITHHOLD_SECTION_D        ("Withholding Section D", String.class),
	MN_W4_WITHHOLD_SECTION_E        ("Withholding Section E", String.class),
	MN_W4_WITHHOLD_SECTION_F        ("Withholding Section F", String.class),
	MN_W4_ALLOW_SECTION_TOTAL       ("Allow Section Total", Integer.class),
	MN_W4_WITHHOLD_SECTION_TOTAL    ("Withholding Section Total", String.class),
	MN_W4_DOMICILE_LINE             ("Domicile line", String.class),
	MN_W4_DAY_TIME_PHONE_NUM        ("Day time phone number", String.class),
	
	// MO-W4 fields
	MOW4_REDUCED_WITHHOLD			("Reduced withholding", Integer.class), 
	MOW4_EXMPT_CHOICE               ("Exempt choice check", String.class),
	
	// MS-W4 fields
	MS_W4_OLDER_HUSBAND					("Older Husband", Boolean.class),
	MS_W4_OLDER_WIFE					("Older Wife", Boolean.class),
	MS_W4_OLDER_SINGLE					("Older Single", Boolean.class),
	MS_W4_BLIND_HUSBAND					("Blind Husband", Boolean.class),
	MS_W4_BLIND_WIFE					("Blind Wife", Boolean.class),
	MS_W4_BLIND_SINGLE					("Blind Single", Boolean.class),

    // MT W4 fields
	MT_W4_ALLOWANCE_SECTION_TOTAL      ("Allowance Section Total", String.class),
	
	// NJ W4 fields
	NJ_W4_SINGLE                      ("Single", Boolean.class),
	NJ_W4_UNION_COUPLE_JOINT          ("Union Couple Joint", Boolean.class),
	NJ_W4_UNION_COUPLE_SEP            ("Union Couple Seperate", Boolean.class),
	NJ_W4_HEAD_HOUSE                  ("Head of House", Boolean.class),
	NJ_W4_WIDOWER                     ("Widower", Boolean.class),
	NJ_W4_CLAIM                       ("Claim", String.class),
	NJ_W4_INSTRUCTION_LETTER          ("Instruction Letter", String.class),
	
	NYW4_FIRST_AND_MIDDLE	("First name and middle initial", String.class),
	NYW4_NYC_RESIDENT       ("Resident of New York City", Boolean.class),
	NYW4_YONKERS_RESIDENT   ("Resident of yonkers", Boolean.class),
	NYW4_NYC_ALLOWANCES     ("Allowances for NYC", Integer.class),
	NYW4_NYS_AMOUNT         ("New York State amount", Integer.class),
	NYW4_NYC_AMOUNT         ("New York city amount", Integer.class),
	NYW4_YONKERS_AMOUNT     ("Yonkers amount", Integer.class),
	NYW4_EMP_CLAIMED_NYS    ("Employee claimed allowances for NYS ", Boolean.class),
	NYW4_EMP_NEW_HIRE       ("Employee is a new hire ", Boolean.class),
	NYW4_DEP_HEALTH_INSURANCE("Dependent health insurance", Boolean.class),
	NYW4_FIRST_PAY_DATE		("Employee's first pay date", Date.class),
	NYW4_EMPLOYEE_QUALIFY_DATE("Employee's qualifying date for health insurance", Date.class),
	NYW4_EMPLOYER_NAME_ADDR ("Employer's name and address", String.class),

	//OH-W4 field
	OHW4_SCHOOL_DIS_NAME             ("School district of residence", String.class),
	OHW4_SCHOOL_DIS_No               ("School district no", String.class),

	// OK-W4 LS-3849
	OK_W4_MARIED_WITHHOLD           ("Married Withhold", Boolean.class),
	OK_W4_ALLOWANCE_SECTION_A       ("Allowance Section A", String.class),
	OK_W4_ALLOWANCE_SECTION_B       ("Allowance Section B", String.class),
	OK_W4_ALLOWANCE_SECTION_C       ("Allowance Section C", String.class),
	OK_W4_ALLOWANCE_SECTION_D       ("Allowance Section D", String.class),
	OK_W4_ALLOWANCE_SECTION_E       ("Allowance Section E", String.class),
	OK_W4_ALLOWANCE_SECTION_TOTAL   ("Allowance Section F", String.class),
	OK_W4_EMPLOYER_YES              ("Employer Yes", Boolean.class),
	OK_W4_EMPLOYER_NO               ("Employer No", Boolean.class),
	OK_W4_ALLOW_EXEMPTIONS_A        ("Allowance Excemption A", String.class),
	OK_W4_ALLOW_EXEMPTIONS_B        ("Allowance Excemption B", String.class),
	OK_W4_ALLOW_EXEMPTIONS_C        ("Allowance Excemption C", String.class),
	
	// OR-W4 field
	ORW4_RE_DETERMINATION    		("Redetermination", Boolean.class),
	ORW4_EX_CODE             		("Exemption code", String.class),

	//PR W4 fields
	PRW4_OPTIONAL_TAX_COMPUTATION					("Employer does the tax computation", Boolean.class),
	PRW4_MIL_SPOUSE_RELIEF_ACT					("Military spouse residency relief act", Boolean.class),
	PRW4_EMPLOYER_NOT_CONSIDER_WITHHOLDING		("Employer does not consider withholding on first part of earned income", Boolean.class),
	PRW4_VET_EXEMPTION_STATUS						("Veteran exemption status", String.class),
	PRW4_VET_NONE_EXEMPTION_STATUS				("Veteran exemption status with less withholding", String.class),
	PRW4_HOME_MORTGAGE_INTERESTS_ALLOWANCE		("Home mortgage interest allowance", Integer.class),
	PRW4_CHARITABLE_CONTRIBUTIONS_ALLOWANCE		("Charitable contributions allowance", Integer.class),
	PRW4_MEDICAL_EXPENSES_ALLOWANCE				("Medical expenses allowance", Integer.class),
	PRW4_STUDENT_LOANS_ALLOWANCE					("Student loan interest allowance", Integer.class),
	PRW4_GOV_PENSION_CONTRIBUTION_ALLOWANCE		("Government pension allowance", Integer.class),
	PRW4_INDIV_RETIREMENT_CONTRIBUTIONS_ALLOWANCE	("Individual retirement allowance", Integer.class),
	PRW4_EDUCATION_CONTRIBUTION_ALLOWANCE			("Educational contribution allowance", Integer.class),
	PRW4_HEALTH_SAVINGS_ACCTS_ALLOWANCE			("Health savings account contribution allowance", Integer.class),
	PRW4_CAUSALTY_RESIDENCE_LOSS_ALLOWANCE		("Caualty residenncial loss allowance", Integer.class),
	PRW4_PERSONAL_PROPERTY_LOSS_ALLOWANCE			("Home mortgage interest allowance", Integer.class),
	PRW4_AUTH_EMPLOYER_PAY_PERIOD_WITHHOLDING		("Authorize the employer to take withholding on a pay period basis", Boolean.class),
	PRW4_EMPLOYER_WITHHOLDING_PAY_PERIOD_AMT		("Amount that employer will withhold per pay period", Integer.class),
	PRW4_EMPLOYER_WITHHOLDING_PAY_PERIOD_PERCENT	("Percentage that employer will withhold per pay period", Integer.class),
	PRW4_JOINT_CUSTODY_DEPENDENTS					("Number of dependents that can be claimed by two people", Integer.class),
	PRW4_EMPLOYEE_PARTICIPATE_GOV_PENSION			("Whether or not the employee participates in a government pension program", Boolean.class),
	PRW4_AMT_TOTAL_ALLOWANCES						("Total amount of allowances", Integer.class),

	//RI W4 field
	RI_W4_PERSNL_EXEMPTIONS          ("Personal Exemption", String.class),

	//SC-W4 fields
	SC_W4_LASTNAME_DIFF			    ("If lastname is Different on social security card", Boolean.class),
	SC_W4_CHECK_EXEMPTION			("The exempt check", Boolean.class),
	SC_W4_DOMICILE_CHECK			("The Domicile check", Boolean.class),
		
	// VA W4 fields
	VAW4_BLINDNESS_EXEMPT           ("Blindness Exemption", String.class),
	VAW4_TOTAL_EXEMPT               ("Total Exemption", String.class),
	VAW4_8A                         ("8A", String.class),
	VAW4_8B                         ("8B", String.class),	// NY W4 Fields
	
	//WV W4 field
	WVW4_CERT_STATE_OR_RESIDENCE	("Certified state of residence", String.class),
	// (end of individual state W4 field types)

	// W-9 Fields
	W9_FATCA_CODE			("FATCA Reporting Code", String.class),
	W9_EXEMPT_PAYEE_CODE	("Exempt Payee Code", Integer.class),
	W9_INDIVIDUAL			("Individual", String.class),
	W9_LLC					("Limited Liability Corp", String.class),
	W9_OTHER_TAX_CLASS		("Other Tax Classification", String.class), // TODO change this (or next) so this is not subset of next
	W9_OTHER_TAX_CLASSES	("Other Tax Classifications", String.class),
	W9_PARTNERSHIP			("Partnership", String.class),
	W9_C_CORP				("C Corp", String.class),
	W9_S_CORP				("S Corp", String.class),
	W9_TAX_CLASS_TYPES		("Tax Classification Type", String.class),
	W9_TRUST_ESTATE			("Trust/Estate", String.class),
	W9_REQUESTER			("Requester's Name & Address", String.class),

	// CA and NY WTPA Fields
	WTPA_NAME						("Name", String.class),
	WTPA_START_DATE					("Start Date", Date.class),
	WTPA_EMAIL						("Email", String.class),
	WTPA_PHONE						("Phone", String.class),
	WTPA_OCCUPATION					("Occupation", String.class),
	WTPA_PROJECT_NAME				("Project Name", String.class),
	WTPA_PROJECT_NUMBER				("Project Number", String.class),
	WTPA_EMPLOYER_NAME				("Employer Name", String.class),
	WTPA_DBA						("Dba", String.class),
	WTPA_FEDID_NUMBER				("Employer Fed Id Number", String.class),
	WTPA_ADDRESS_LINE1				("Address Line1", String.class),
	WTPA_ADDRESS_CITY_ONLY			("Address City", String.class),
	WTPA_ADDRESS_STATE				("Address State", String.class),
	WTPA_ADDRESS_ZIP				("Address Zip", String.class),
	WTPA_ADDRESS_CITY_STATE_ZIP		("Address City State Zip", String.class),
	WTPA_MAILING_ADDRESS_LINE1		("Mailing Address Line1", String.class),
	WTPA_MAILING_ADDRESS_CITY_ONLY	("Mailing Address City", String.class),
	WTPA_MAILING_ADDRESS_STATE		("Mailing Address Stae", String.class),
	WTPA_MAILING_ADDRESS_ZIP		("Mailing Address Zip", String.class),
	WTPA_MAILING_ADDRESS_CITY_STATE_ZIP("Mailing Address City State Zip", String.class),
	WTPA_EMPLOYER_PHONE				("Employer Phone", String.class),
	WTPA_PAYROLL_TEXT				("Payroll text", String.class),
	WTPA_RATE_CHANGE				("Rate Change", String.class), // checkbox
	WTPA_REGULAR_RATE				("Regular Rate", BigDecimal.class),
	WTPA_REGULAR_FREQ_BTN			("Regular Freq", String.class),
	WTPA_REGULAR_FREQ_HOUR			("Regular Freq: Hour", String.class),
	WTPA_REGULAR_FREQ_DAY			("Regular Freq: Day", String.class),
	WTPA_REGULAR_FREQ_OTHER			("Regular Freq: Other", String.class),
	WTPA_REGULAR_FREQ_EXPLAIN		("Regular Freq: Other (Explain)", String.class),
	WTPA_DAILY_HOURS				("Daily Hours", BigDecimal.class),
	WTPA_OVERTIME_METHOD_BTN		("Overtime Method", String.class),
	WTPA_OVERTIME_METHOD_WEEKLY		("Overtime Method : Weekly", String.class),
	WTPA_OVERTIME_METHOD_DAILY		("Overtime Method : Daily", String.class),
	WTPA_OVERTIME_RATE				("Overtime Rate", BigDecimal.class),
	WTPA_OVERTIME_FREQ_BTN			("Overtime Freq", String.class),
	WTPA_OVERTIME_FREQ_HOUR			("Overtime Freq: Hour", String.class),
	WTPA_OVERTIME_FREQ_OTHER		("Overtime Freq: Other", String.class),
	WTPA_OVERTIME_FREQ_EXPLAIN		("Overtime Freq: Other (explain)", String.class),
	WTPA_OVERTIME_TIER1_HRS			("Overtime Tier1", BigDecimal.class),
	WTPA_OVERTIME_TIER1_AMT			("Overtime Tier1 Amt", BigDecimal.class),
//	WTPA_OVERTIME					("Overtime", String.class),
	WTPA_OVERTIME_TIER2_HRS			("Overtime Tier2", BigDecimal.class),
	WTPA_OVERTIME_TIER2_AMT			("Overtime Tier2 Amt", BigDecimal.class),
	WTPA_UNION_CONTRACT				("Has Agreement", String.class), // for checkbox
	WTPA_CBA_NONEX_AGREEMENT		("CBA Agreement", String.class),
	WTPA_EXEMPT_PAY_TYPE_BTN		("Exempt Pay Type", String.class),
	WTPA_EXEMPT_PAY_TYPE_HOURLY		("Exempt Pay Type: Hourly", String.class),
	WTPA_EXEMPT_PAY_TYPE_SALARY		("Exempt Pay Type: Salary", String.class),
	WTPA_EXEMPT_PAY_TYPE_DAYRATE	("Exempt Pay Type: Day Rate", String.class),
	WTPA_EXEMPT_PAY_TYPE_PIECERATE	("Exempt Pay Type: Piece Rate", String.class),
	WTPA_EXEMPT_PAY_TYPE_OTHER		("Exempt Pay Type: Other", String.class),
	WTPA_EXEMPT_PAY_AMT				("Exempt Pay Amt", BigDecimal.class),
	WTPA_IS_EXEMPT					("Is Exempt", String.class),
	WTPA_EXEMPT_REASON				("Exempt Reason", String.class),
	WTPA_HAS_CBA					("Has CBA Agreement", String.class), // for checkbox
	WTPA_CBA_EX_AGREEMENT			("CBA Agreement", String.class),
	WTPA_EXEMPT_INFO_AT				("Exempt Info At", String.class),
	WTPA_ALLOW_NONE					("Allow None", String.class),
	WTPA_ALLOW_TIPS_CHK				("Allow Tips", String.class),
	WTPA_ALLOW_TIPS_AMT				("Allow Tips Amt", BigDecimal.class),
	WTPA_ALLOW_MEAL_CHK				("Allow Meal", String.class),
	WTPA_ALLOW_MEAL_AMT				("Allow Meal Amt", BigDecimal.class),
	WTPA_ALLOW_LODGING_CHK			("Allow Lodging", String.class),
	WTPA_ALLOW_LODGING_AMT			("Allow Lodging Amt", BigDecimal.class),
	WTPA_ALLOW_OTHER_CHK			("Allow Other", String.class),
	WTPA_ALLOW_OTHER_AMT			("Allow Other Amt", BigDecimal.class),
	WTPA_REGULAR_PAY_DAY			("Regular Pay Day", Byte.class),
	WTPA_PAYDAY_FREQ_BTN			("Payday Freq", String.class),
	WTPA_PAYDAY_FREQ_WEEKLY			("Payday Freq: Weekly", String.class),
	WTPA_PAYDAY_FREQ_BIWEEKLY		("Payday Freq: Bi Weekly", String.class),
	WTPA_PAYDAY_FREQ_OTHER			("PayDay Freq: Other", String.class),
	WTPA_PAYDAY_FREQ_EXPLAIN		("Payday Freq: Other (if more frequent)", String.class),
	WTPA_NOTICE_GIVEN_AT_HIRE		("Notice Given At Hire", String.class),
	WTPA_NOTICE_GIVEN_WITHIN_7_DAYS	("Notice Given Within 7 days", String.class),
//	WTPA_SICK_LEAVE_TYPE_BTN		("Sick Leave Type", String.class), // not used. LS-1550
	WTPA_SICK_LEAVE_TYPE			("Sick Leave Type", String.class),
//	WTPA_SICK_LEAVE_TYPE_CA			("Sick Leave Type: Accrues Ca", String.class),
//	WTPA_SICK_LEAVE_TYPE_POLICY		("Sick Leave Type: Accrues Policy", String.class),
//	WTPA_SICK_LEAVE_TYPE_PLUS_24	("Sick Leave Type: Accrues 24 Plus", String.class),
//	WTPA_SICK_LEAVE_TYPE_EXEMPT		("Sick Leave Type: Exempt", String.class),
	WTPA_SICK_LEAVE_REASON			("Sick Leave Reason", String.class),
	WTPA_PAY_NOTICE_ENGLISH			("Pay Notice English", String.class),
	WTPA_PAY_NOTICE_PRIMARY_LANG	("Pay Notice Primary Lang", String.class),
	WTPA_EMPLOYEE_DECLINES_SIGN		("Employee Declines Sign", String.class),
	WTPA_EMPLOYEE_REP_PHONE			("Employee Rep Phone", String.class),
	WTPA_EMPLOYEE_REP_NAME			("Employee Rep Name", String.class),
	WTPA_EMPLOYEE_REP_TITLE			("Employee Rep Title", String.class),
	WTPA_EMPLOYEE_REP_EMAIL			("Employee Rep Email", String.class),

	// Direct Deposit fields
	DD_1ST_BANK						("First Bank", String.class),
	DD_2ND_BANK						("Second Bank", String.class),
	DD_CHANGE_ACCT					("Change Account", String.class),
	DD_STOP							("Stop Deposit", String.class),
	DD_CONFIRM						("Confirm Request", String.class),
	DD_BANK_INITIAL1				("Bank Initial 1", Integer.class),
	//DD_ACCT_TYPE1					("Account Type 1", String.class),
	DD_ACCT_TYPE1_CHCK				("Account Type 1 Checkings", String.class),
	DD_ACCT_TYPE1_SAV				("Account Type 1 Savings", String.class),
	DD_ACCT_NAME1					("Account Name 1", String.class),
	DD_ACCT_NUMBER1					("Account Number 1", String.class),
	DD_ABA_ROUTING1					("ABA Routing 1", String.class),
	DD_BANK_NAME1					("Bank Name 1", String.class),
	DD_BANK_PHONE1					("Bank Phone 1", String.class),
	DD_BANK_ADDR1					("Bank Addres 1", String.class),
	DD_BANK_INITIAL2				("Bank Initial 2", Integer.class),
	DD_BANK_AMT_PERCENT				("Bank Amount or Percent", Boolean.class), // LS-3477
	DD_BANK_AMOUNT2					("Bank 2 Amount", BigDecimal.class),	// LS-3477
	//DD_ACCT_TYPE2					("Account Type 2", String.class),
	DD_ACCT_TYPE2_CHCK				("Account Type 2 Checkings", String.class),
	DD_ACCT_TYPE2_SAV				("Account Type 2 Savings", String.class),
	DD_ACCT_NAME2					("Account Name 2", String.class),
	DD_ACCT_NUMBER2					("Account Number 2", String.class),
	DD_ABA_ROUTING2					("ABA Routing 2", String.class),
	DD_BANK_NAME2					("Bank Name 2", String.class),
	DD_BANK_PHONE2					("Bank Phone 2", String.class),
	DD_BANK_ADDR2					("Bank Addres 2", String.class),
	//DD_OLD_ACCT_TYPE				("Old Account Type ", String.class),
	DD_OLD_ACCT_TYPE_CHCK			("Old Account Type Checkings", String.class),
	DD_OLD_ACCT_TYPE_SAV			("Old Account Type Savings", String.class),
	DD_OLD_ACCT_NAME				("Old Account Name", String.class),
	DD_OLD_ACCT_NUMBER				("Old Account Number", String.class),
	DD_OLD_ABA_ROUTING				("Old ABA Routing", String.class),
	DD_OLD_BANK_NAME				("Old Bank Name", String.class),
	DD_SIGNATURE1_NAME				("Direct Deposit Employee Signature 1", String.class),
	DD_SIGNATURE1_DATE 				("Direct Deposit Employee Signature Date 1", Date.class),
	DD_SIGNATURE2_NAME				("Direct Deposit Employee Signature 2", String.class),
	DD_SIGNATURE2_DATE 				("Direct Deposit Employee Signature Date 2", Date.class),
	DD_LOAN_OUT_NAME                ("Loan out name", String.class),
	DD_FEIN                         ("Fein no.", String.class),

	// Payroll Start fields (or My Account 'defaults'); LS-
	PS_ACCT_CODE_LOC					("Account code - Loc", String.class),
	PS_ACCT_CODE_MAJOR					("Account code - Major", String.class), // same as Prod/Epi
	PS_ACCT_CODE_SET					("Account code - Set", String.class),
	PS_ACCT_CODE_DETAIL					("Account code - Detail", String.class),
	PS_ACCT_CODE_SUB					("Account code - Sub", String.class),
	PS_ACCT_CODE_PREP					("Account code - Prep/wrap", String.class),
	PS_ACCT_CODE_SHOOT					("Account code - Shoot", String.class),

	LOAN_OUT_CORP_NAME					("Loan-out Corp Name", String.class),
	LOAN_OUT_FEDID_NUMBER				("Loan-out Fed Id Number", String.class), // TODO - change so this is not prefix of next two fields
	LOAN_OUT_FEDID_NUMBER_2				("Loan-out Fed Id Number, 1st 2 digits", String.class),
	LOAN_OUT_FEDID_NUMBER_7				("Loan-out Fed Id Number, last 7 digits", String.class),
	LOAN_OUT_SIGNER_NAME				("Loan-out Signer's Name", String.class), // who signs for the Loan-out corp; should auto-fill with employee name
	LOAN_OUT_STREET 					("Loan-out address - Street address", String.class),
	LOAN_OUT_ADDR_2 					("Loan-out address - Street address line 2", String.class),
	LOAN_OUT_CITY_ONLY 					("Loan-out address - City name", String.class),
	LOAN_OUT_STATE 						("Loan-out address - State 			(2-letter code)", String.class),
	LOAN_OUT_ZIP 						("Loan-out address - Zip code", String.class),
	LOAN_OUT_CITY_STATE_ZIP				("Loan-out address as 'city, state zip'", String.class),
	LOAN_OUT_INCORP_STATE 				("Loan-out Incorporation state", String.class),
	LOAN_OUT_INCORP_DATE 				("Loan-out Incorporation date", Date.class),
	LOAN_OUT_TAXID_STATE				("Loan-out state tax ID number", String.class),
	LOAN_OUT_VALID_IN_CA 				("Loan-out is valid in CA", Boolean.class),
	LOAN_OUT_VALID_IN_NY 				("Loan-out is valid in NY", Boolean.class),
	LOAN_OUT_VALID_OTHERS 				("Loan-out - other valid states list", String.class),
	LOAN_OUT_VALID_ALL 					("Loan-out - all valid states list", String.class),
	// LS-3825 Additional fields for filling Payroll Start form pdf
	LOAN_OUT_MAILING_STREET 			("Loan-out mailing address - Street address", String.class),
	LOAN_OUT_MAILING_ADDR_2 			("Loan-out mailing address - Street address line 2", String.class),
	LOAN_OUT_MAILING_CITY_ONLY 			("Loan-out mailing address - City name", String.class),
	LOAN_OUT_MAILING_STATE 				("Loan-out mailing address - State 			(2-letter code)", String.class),
	LOAN_OUT_MAILING_ZIP 				("Loan-out mailing address - Zip code", String.class),
	LOAN_OUT_MAILING_CITY_STATE_ZIP		("Loan-out mailing address as 'city, state zip'", String.class),
	LOAN_OUT_TAX_CLASSIFICATION			("Tax Classification", String.class),
	LOAN_OUT_LLC_TYPE					("Type of LLC- S or C corp", String.class),
	LOAN_OUT_PHONE						("Corp Phone Number", String.class),
	
	PS_DOB_MDY							("Date of birth as mm/dd/yyyy", Date.class),
	PS_TYPE_GENDER						("Gender", String.class),
	PS_DESC_GENDER						("Gender Desc", String.class),
	PS_MINOR							("Minor", String.class),
	PS_WORK_CITY						("Work City", String.class),
	PS_WORK_STATE						("Work State", String.class),
	PS_HIRE_DATE_MDY 					("Hire date as mm/dd/yyyy", Date.class),
	PS_ACA_FULL_TIME					("ACA - Full time", Boolean.class),
	PS_ACA_VARIABLE_TIME				("ACA - Variable time", Boolean.class),
	PS_ACA_PART_TIME					("ACA - Part time", Boolean.class),
	PS_ACA_SEASONAL						("ACA - Seasonal", Boolean.class),
	PS_ACA_BASIS						("ACA Employment Basis", String.class),
	UNION_LOCAL							("Union local number", String.class),
	PS_OCC_CODE							("Occupation code", String.class),
	PS_SCHEDULE_LETTER					("Contract schedule letter", String.class),
	PS_HOURLY_STUDIO_RATE				("Hourly studio rate", BigDecimal.class),
	PS_HOURLY_DISTANT_RATE				("Hourly distant rate", BigDecimal.class),
	DAILY_RATE							("Exempt Daily Rate", BigDecimal.class),
	DAILY_DISTANT_RATE					("Exempt Daily Rate", BigDecimal.class),
	WEEKLY_OR_HOURLY_RATE				("Hourly, or Exempt Weekly, Rate", BigDecimal.class),
	WEEKLY_RATE							("Exempt Weekly Rate", BigDecimal.class),
	WEEKLY_DISTANT_RATE					("Exempt Weekly Rate", BigDecimal.class),
	PS_BOX_RENTAL_STUDIO				("Box Rental (studio)", BigDecimal.class),
	PS_BOX_RENTAL_DISTANT				("Box Rental (distant)", BigDecimal.class),
	PS_CAR_ALLOWANCE_STUDIO				("Car Allowance (studio)", BigDecimal.class),
	PS_CAR_ALLOWANCE_DISTANT			("Car Allowance (distant)", BigDecimal.class),
	PS_GUAR_STUDIO_HOURS				("Hours", BigDecimal.class),
	PS_GUAR_DISTANT_HOURS				("Hours", BigDecimal.class),
	// LS-3825 Additional fields for filling Payroll Start form pdf
	PS_PAID_AS							("Paid as Individual or Loan-out", String.class),
	PS_FORM_TYPE						("Type of form: new, changed, deleted", String.class),
	PS_CREATION_DATE					("Date the form was created MM/dd/yyyy", Date.class),
	PS_DOC_ID							("Document ID", String.class),
	PS_START_DATE_MDY 					("Start date as mm/dd/yyyy", Date.class),
	PS_END_DATE_MDY 					("End date as mm/dd/yyyy", Date.class),
	PS_EFFECTIVE_FROM_DATE_MDY 			("Effective From date as mm/dd/yyyy", Date.class),
	PS_EFFECTIVE_TO_DATE_MDY 			("Effective To date as mm/dd/yyyy", Date.class),
	PS_WORK_COUNTRY						("Work country code", String.class),
	PS_WORK_ZIP							("Work zip code", String.class),
	PS_JOB_NAME							("Job name", String.class),
	PS_JOB_NUMBER						("Job number", String.class),
	PS_JOB_CLASS						("Job class", String.class),
	PS_OFF_PRODUCTION					("Off production", String.class),
	PS_AGENT							("Agent check box", String.class),
	PS_RETIREMENT						("Retirement account if any", String.class),
	PS_ETHNICITY						("Ethnicity code", String.class),
	PS_EMPLOYMENT_TYPE					("Exempt rate : weekly, daily", String.class),
	PS_EXEMPT_RATE						("Type of employment : weekly, daily", BigDecimal.class),
	PS_EXEMPT_TYPE						("Type of employment : weekly, daily", String.class),
	PS_PAY_6_7_DAY						("Pay 6/7th day label", String.class),
	PS_PAY_6_7_CHECK					("Pay 6/7th day check box", Boolean.class),
	PS_OVERTIME_RATE_1					("Overtime rate 1", String.class),
	PS_OVERTIME_RATE_2					("Overtime rate 2", String.class),
	PS_OVERTIME_AFTER_RATE_1			("Overtime after rate 1", String.class),
	PS_OVERTIME_AFTER_RATE_2			("Overtime after rate 2", String.class),
	PS_OVERTIME_AFTER_RATE_3			("Overtime after rate 3", String.class),
	PS_OVERTIME_AFTER_1					("Overtime after 1", String.class),
	PS_OVERTIME_AFTER_2					("Overtime after 2", String.class),
	PS_OVERTIME_AFTER_3					("Overtime after 3", String.class),
	PS_MULTIPLIER_1						("Multiplier 1", String.class),
	PS_MULTIPLIER_2						("Multiplier 2", String.class),
	PS_MULTIPLIER_3						("Multiplier 3", String.class),
	PS_PROD_NAME						("Production company name", String.class),
	PS_HOURLY_RATE						("Hourly rate for distant or studio", BigDecimal.class),
	PS_GUAR_HOURS						("Guaranteed Hours", BigDecimal.class),
	PS_SEP_CHECK_BOX					("Separate Check for Box Rental", Boolean.class),
	PS_SEP_CHECK_CAR					("Separate Check for Car Allowance", Boolean.class),
	PS_SEP_CHECK_MEAL					("Separate Check for Meal Allowance", Boolean.class),
	PS_BOX_RENTAL_FREQ					("Box Rental frequency", String.class),
	PS_BOX_RENTAL_MAX					("Box Rental Max Amount", BigDecimal.class),
	PS_BOX_RENTAL_ACCT_FREE				("Box Rental Account Free code", String.class),
	PS_BOX_RENTAL_ACCT_MAJOR			("Box Rental Account Major code", String.class),
	PS_CAR_ALLOWANCE_FREQ				("Car Allowance Frequency", String.class),
	PS_CAR_ALLOWANCE_MAX				("Car Allowance Max Amount", BigDecimal.class),
	PS_CAR_ALLOWANCE_ACCT_FREE			("Car Allowance Account Free code", String.class),
	PS_CAR_ALLOWANCE_ACCT_MAJOR			("Car Allowance Account Major code", String.class),
	PS_MEAL_ALLOWANCE_STUDIO			("Meal Allowance (studio)", BigDecimal.class),
	PS_MEAL_ALLOWANCE_DISTANT			("Meal Allowance (distant)", BigDecimal.class),
	PS_MEAL_ALLOWANCE_FREQ				("Meal Allowance Frequency", String.class),
	PS_MEAL_ALLOWANCE_ACCT_FREE			("Meal Allowance Account Free code", String.class),
	PS_MEAL_ALLOWANCE_ACCT_MAJOR		("Meal Allowance Account Major code", String.class),
	PS_PER_DIEM_NON_TAX_DISTANT			("Per Diem Non-Taxable (distant)", BigDecimal.class),
	PS_PER_DIEM_NON_TAX_FREQ			("Per Diem Non-Taxable Frequency", String.class),
	PS_PER_DIEM_NON_TAX_ACCT_FREE		("Per Diem Non-Taxable Account Free code", String.class),
	PS_PER_DIEM_NON_TAX_ACCT_MAJOR		("Per Diem Non-Taxable Account Major code", String.class),
	PS_PER_DIEM_TAX_DISTANT				("Per Diem Taxable (distant)", BigDecimal.class),
	PS_PER_DIEM_TAX_FREQ				("Per Diem Taxable Frequency", String.class),
	PS_PER_DIEM_TAX_ACCT_FREE			("Per Diem Taxable Account Free code", String.class),
	PS_PER_DIEM_TAX_ACCT_MAJOR			("Per Diem Taxable Account Major code", String.class),
	PS_PER_DIEM_ADV_DISTANT				("Per Diem Advance (distant)", BigDecimal.class),
	PS_PER_DIEM_ADV_FREQ				("Per Diem Advance Frequency", String.class),
	PS_PER_DIEM_ADV_ACCT_FREE			("Per Diem Advance Per Diem Advance Account Free code", String.class),
	PS_PER_DIEM_ADV_ACCT_MAJOR			("Per Diem Advance Account Major code", String.class),
	PS_MEAL_MONEY_STUDIO				("Meal Money (studio)", BigDecimal.class),
	PS_MEAL_MONEY_DISTANT				("Meal Money (distant)", BigDecimal.class),
	PS_MEAL_MONEY_FREQ					("Meal Money Frequency", String.class),
	PS_MEAL_MONEY_ACCT_FREE				("Meal Money Account Free code", String.class),
	PS_MEAL_MONEY_ACCT_MAJOR			("Meal Money Account Major code", String.class),
	PS_MEAL_MONEY_ADV_STUDIO			("Meal Money Advance (studio)", BigDecimal.class),
	PS_MEAL_MONEY_ADV_DISTANT			("Meal Money Advance (distant)", BigDecimal.class),
	PS_MEAL_MONEY_ADV_FREQ				("Meal Money Advance Frequency", String.class),
	PS_MEAL_MONEY_ADV_ACCT_FREE			("Meal Money Advance Account Free code", String.class),
	PS_MEAL_MONEY_ADV_ACCT_MAJOR		("Meal Money Advance Account Major code", String.class),
	PS_MEAL_PENALTY_ACCT_FREE			("Meal Penalty Account Free code", String.class),
	PS_MEAL_PENALTY_ACCT_MAJOR			("Meal Penalty Account Major code", String.class),
	PS_FRINGE_ACCT_FREE					("Fringe Account Free code", String.class),
	PS_FRINGE_ACCT_MAJOR				("Fringe AdvanceAccount Major code", String.class),
	PS_OTHER_FEES_LBL					("Other Fees label shown when employee is a cast member", String.class),
	PS_REUSE_LBL						("Reuse label shown when employee is a cast member", String.class),
	PS_REUSE_FEE						("Reuse Fee Ammount shown when employee is a cast member", String.class),
	PS_ACTOR_AGENT_COMMISION_LBL		("Agent Commission label shown when employee is a cast member", String.class),
	PS_ACTOR_AGENT_COMMISION_AMT		("Agent Commission shown when employee is a cast member", String.class),
	PS_PREP_EXEMPT_RATE					("Prep Type of employment rate: weekly, daily", BigDecimal.class),
	PS_PREP_EXEMPT_TYPE					("Prep Type of employment : weekly, daily", String.class),
	PS_PREP_PAY_6_7_DAY					("Prep Pay 6/7th day label", String.class),
	PS_PREP_PAY_6_7_CHECK				("Prep Pay 6/7th day check box", Boolean.class),
	PS_PREP_OVERTIME_RATE_1				("Prep Overtime rate 1", String.class),
	PS_PREP_OVERTIME_RATE_2				("Prep Overtime rate 2", String.class),
	PS_PREP_OVERTIME_AFTER_RATE_1		("Prep Overtime after rate 1", String.class),
	PS_PREP_OVERTIME_AFTER_RATE_2		("Prep Overtime after rate 2", String.class),
	PS_PREP_OVERTIME_AFTER_RATE_3		("Prep Overtime after rate 3", String.class),
	PS_PREP_OVERTIME_AFTER_1			("Prep Overtime after 1", String.class),
	PS_PREP_OVERTIME_AFTER_2			("Prep Overtime after 2", String.class),
	PS_PREP_OVERTIME_AFTER_3			("Prep Overtime after 3", String.class),
	PS_PREP_MULTIPLIER_1				("Prep Multiplier 1", String.class),
	PS_PREP_MULTIPLIER_2				("Prep Multiplier 2", String.class),
	PS_PREP_MULTIPLIER_3				("Prep Multiplier 3", String.class),
	PS_PREP_GUAR_HOURS					("Prep Guaranteed Hours", String.class),
	PS_PREP_HOURLY_RATE					("Prep Hourly rate for distant or studio", String.class),
	PS_PREP_EMPLOYMENT_TYPE				("Prep Employment type : hourly, daily, weekly", String.class),

	// ACTRA (Canada) Contract
	// Section A & B
	ACTRA_CONTRACT_NUM						("Actra Contract Num", String.class),
	ACTRA_BRANCH_CODE						("Actra Branch Code", String.class),
	AGENCY_COMPANY_NAME						("Agency Name", String.class),
	AGENCY_PRODUCER							("Agency Producer", String.class),
	AGENCY_ADDRESS_COMPLETE					("Agency Full Address", String.class),
	ADVERTISER_NAME							("Advertiser Name", String.class),
	PRODUCT_NAME							("Product Name", String.class),
	PROD_HOUSE_NAME							("Prod House Name", String.class),
	PROD_HOUSE_ADDRESS_COMPLETE				("Prod House Full Address", String.class),
	PAY_SESSION_FEE							("Pay Session Fee", Boolean.class),
	DIRECTOR_NAME							("Director Name", String.class),
	ACTRA_GST_HST							("Actra Gst Hst", String.class),
	ACTRA_QST								("Actra Qst", String.class),
	TALENT_AGENCY_NAME						("Talent Agency Name", String.class),
	AGENCY_CONTACT							("Agency Contact", String.class),
	ACTRA_DOB_CA 							("Date of birth as yyyy-mm-dd", Date.class), // for Canada
	PERFORMANCE_CATEGORY					("Performance Category", String.class),
	ACTRA_FULL_MEMBER_NUM					("Actra Full Member Num", String.class),
	ACTRA_APPRENTICE_NUM					("Actra Apprentice Num", String.class),
	ACTRA_WORK_PERMIT_NUM					("Actra Work Permit Num", String.class),
	ACTRA_NATIONAL_TV						("Actra National Tv", String.class),
	ACTRA_NATIONAL_RADIO					("Actra National Radio", String.class),
	ACTRA_NATIONAL_DIGITAL_MEDIA_VIDEO		("Actra National Digital Media Video", String.class),
	ACTRA_NATIONAL_DIGITAL_MEDIA_AUDIO		("Actra National Digital Media Audio", String.class),
	ACTRA_TAGS_TV							("Actra Tags Tv", String.class),
	ACTRA_TAGS_RADIO						("Actra Tags Radio", String.class),
	ACTRA_TAGS_DIGITAL_MEDIA				("Actra Tags Digital Media", String.class),
	ACTRA_REGIONAL_CHANGES_TV				("Actra Regional Changes Tv", String.class),
	ACTRA_REGIONAL_CHANGES_RADIO			("Actra Regional Changes Radio", String.class),
	ACTRA_REGIONAL_CHANGES_DIGITAL_MEDIA	("Actra Regional Changes Digital Media", String.class),
	ACTRA_PSA_TV							("Actra Psa Tv", String.class),
	ACTRA_PSA_RADIO							("Actra Psa Radio", String.class),
	ACTRA_PSA_DIGITAL_MEDIA					("Actra Psa Digital Media", String.class),
	ACTRA_DEMO_TV							("Actra Demo Tv", String.class),
	ACTRA_DEMO_RADIO						("Actra Demo Radio", String.class),
	ACTRA_DEMO_DIGITAL						("Actra Demo Digital", String.class),
	ACTRA_DEMO_PRESENTATION					("Actra Demo Presentation", String.class),
	ACTRA_DEMO_INFOMERCIAL					("Actra Demo Infomercial", String.class),
	ACTRA_SEASONAL_TV						("Actra Seasonal Tv", String.class),
	ACTRA_SEASONAL_RADIO					("Actra Seasonal Radio", String.class),
	ACTRA_SEASONAL_DEALER_A					("Actra Seasonal Dealer A", String.class),
	ACTRA_SEASONAL_DEALER_TV				("Actra Seasonal Dealer Tv", String.class),
	ACTRA_SEASONAL_DEALER_RADIO				("Actra Seasonal Dealer Radio", String.class),
	ACTRA_SEASONAL_DOUBLE_SHOOT				("Actra Seasonal Double Shoot", String.class),
	ACTRA_SEASONAL_JOINT_PROMO				("Actra Seasonal Joint Promo", String.class),
	ACTRA_LOCAL_REGIONAL_CATEGORY_NUM		("Actra Local Regional Category Num", String.class),
	ACTRA_LOCAL_REGIONAL_TV					("Actra Local Regional Tv", String.class),
	ACTRA_LOCAL_REGIONAL_RADIO				("Actra Local Regional Radio", String.class),
	ACTRA_LOCAL_REGIONAL_DIGITAL_MEDIA_A	("Actra Local Regional Digital Media A", String.class),
	ACTRA_LOCAL_REGIONAL_DEMO				("Actra Local Regional Demo", String.class),
	ACTRA_LOCAL_REGIONAL_DIGITAL_MEDIA_BROADCAST  ("Actra Local Regional Digital Media Broadcast", String.class),
	ACTRA_LOCAL_REGIONAL_BROADCAST_DIGITAL_MEDIA  ("Actra Local Regional Broadcast Digital Media", String.class),
	ACTRA_LOCAL_REGIONAL_OTHER				("Actra Local Regional Other", String.class),
	ACTRA_LOCAL_REGIONAL_PILOT_PROJECT		("Actra Local Regional Pilot Project", String.class),
	ACTRA_SHORT_LIFE_TV_7_DAYS				("Actra Short Life Tv 7 Days", String.class),
	ACTRA_SHORT_LIFE_TV_14_DAYS				("Actra Short Life Tv 14 Days", String.class),
	ACTRA_SHORT_LIFE_TV_31_DAYS				("Actra Short Life Tv 31 Days", String.class),
	ACTRA_SHORT_LIFE_TV_45_DAYS				("Actra Short Life Tv 45 Days", String.class),
	ACTRA_SHORT_LIFE_RADIO_7_DAYS			("Actra Short Life Radio 7 Days", String.class),
	ACTRA_SHORT_LIFE_RADIO_14_DAYS			("Actra Short Life Radio 14 Days", String.class),
	ACTRA_SHORT_LIFE_RADIO_31_DAYS			("Actra Short Life Radio 31 Days", String.class),
	ACTRA_SHORT_LIFE_RADIO_45_DAYS			("Actra Short Life Radio 45 Days", String.class),
	ACTRA_TV_BROADCAST_DIGITAL_MEDIA		("Actra Tv Broadcast Digital Media", String.class),
	ACTRA_DIGITAL_MEDIA_BROADCAST_TV		("Actra Digital Media Broadcast Tv", String.class),
	ACTRA_DIGITAL_MEDIA_OTHER				("Actra Digital Media Other", String.class),
	ACTRA_RADIO_DIGITAL_MEDIA				("Actra Radio Digital Media", String.class),
	ACTRA_ONLINE							("Actra Online", String.class),
	ACTRA_PILOT_PROJECT						("Actra Pilot Project", String.class),
	ACTRA_ARTICLE_2403						("Actra Article 2403", String.class),
	ACTRA_ARTICLE_2404						("Actra Article 2404", String.class),
	ACTRA_ARTICLE_2405						("Actra Article 2405", String.class),
	ACTRA_ARTICLE_2406						("Actra Article 2406", String.class),
	COMMERCIAL_NAME							("Commercial Name", String.class),
	ACTRA_DOCKET							("Actra Docket", String.class),
	ACTRA_ADDITIONAL_TITLES					("Actra Additional Titles", String.class),
	SESSION_FEES							("Session Fees", String.class),
	RESIDUAL_FEES							("Residual Fees", String.class),
	OTHER_FEES								("Other Fees", String.class),
	DIGITAL_MEDIA_FEES						("Digital Media Fees", String.class),
	SPECIAL_PROVISIONS						("Special Provisions", String.class),
	SPECIAL_PROVISIONS_SIGNATURE			("Special Provisions Signature", String.class),
	ACTRA_SNACK_YES							("Actra Snack Yes", Boolean.class),
	ACTRA_SNACK_NO							("Actra Snack No", Boolean.class),
	ACTRA_TALENT_INITIAL_AGREE				("Actra Talent Initial Agree", String.class),
	ACTRA_TALENT_INITIAL_DISAGREE			("Actra Talent Initial Disagree", String.class),
	ACTRA_PRODUCER_INITIAL					("Actra Producer Initial", String.class),

	// ACTRA Work Permit
	PERMIT_PROFESSIONAL_NAME				("Actra Work Permit Professional Name", String.class),
	PERMIT_CITIZENSHIP						("Actra Work Permit Citizenship", String.class),
	PERMIT_LEGAL_NAME						("Actra Work Permit Legal Name", String.class),
//	PERMIT_HOME_PHONE						("Actra Work Permit Home Phone", String.class),
//	PERMIT_TALENT_EMAIL_ADDRESS				("Actra Work Permit Talent Email Address", String.class),
//	PERMIT_CELL_PHONE						("Actra Work Permit Cell Phone", String.class),
//	PERMIT_TALENT_ADDRESS					("Actra Work Permit Talent Full Address", String.class),
//	PERMIT_TALENT_AGENCY_NAME				("Actra Work Permit Talent Agency Name", String.class),
//	PERMIT_TALENT_DOB						("Actra Work Permit Talent Dob", Date.class),
	PERMIT_GUARDIAN_NAME					("Actra Work Permit Guardian Name", String.class),
//	PERMIT_SIN_NUM							("Actra Work Permit Sin Num", Integer.class),
	PERMIT_SAG_AFTRA_YES_MEMBER				("Actra Work Permit SAG Aftra Member - yes", Boolean.class),
	PERMIT_SAG_AFTRA_NO_MEMBER				("Actra Work Permit SAG Aftra Member - no", Boolean.class),
	PERMIT_APPRENTICE_YES_MEMBER			("Actra Work Permit Apprentice Member - yes", Boolean.class),
	PERMIT_APPRENTICE_NO_MEMBER				("Actra Work Permit Apprentice Member - no", Boolean.class),
	PERMIT_EQUITY_YES_MEMBER				("Actra Work Permit Equity Member - yes", Boolean.class),
	PERMIT_EQUITY_NO_MEMBER					("Actra Work Permit Equity Member - no", Boolean.class),
	PERMIT_APPRENTICE_NUM					("Actra Work Permit Apprentice Num", String.class),
	PERMIT_ADHERED_ENGAGER					("Actra Work Permit Adhered Engager", String.class),
//	PERMIT_ADVERTISER						("Actra Work Permit Advertiser", String.class),
//	PERMIT_PRODUCTION_HOUSE					("Actra Work Permit Production House", String.class),
//	PERMIT_COMMERCIAL_NAME					("Actra Work Permit Commercial Name", String.class),
	PERMIT_CHAR_NAME_DESC					("Actra Work Permit CharName Desc", String.class),
	PERMIT_MEMBERS_AUDITIONED_NUM			("Actra Work Permit Members Auditioned Num", Integer.class),
	PERMIT_MEMBERS_AUDITIONED_NAMES1		("Actra Work Permit Members Auditioned Names Line 1", String.class),
	PERMIT_MEMBERS_AUDITIONED_NAMES2		("Actra Work Permit Members Auditioned Names Line2", String.class),
	PERMIT_PERFORMANCE_CATEGORY				("Actra Work Permit Performance Category", String.class),
	PERMIT_COM_TYPE_TV						("Actra Work Permit Com Type Tv", Boolean.class),
	PERMIT_COM_TYPE_RADIO					("Actra Work Permit Com Type Radio", Boolean.class),
	PERMIT_COM_TYPE_DIGITAL_MEDIA			("Actra Work Permit Com Type Digital Media", String.class),
	PERMIT_NUM_COM							("Actra Work Permit Num Com", Integer.class),
	PERMIT_COM_DATE							("Actra Work Permit Com Date", Date.class),
	PERMIT_COM_LOCATION						("Actra Work Permit Com Location", String.class),
	PERMIT_APPLICANT_SIGN_ID				("Actra Work Permit Applicant Sign Id", Integer.class),
	PERMIT_WORK_PERMIT_FEE					("Actra Work Permit Work Permit Fee", Double.class),
	PERMIT_PERFORMER_PAID_BY				("Actra Work Permit Paid By - Performer", Boolean.class),
	PERMIT_AGENT_PAID_BY					("Actra Work Permit Paid By - Performer's Agent", Boolean.class),
	PERMIT_PROODUCTION_PAID_BY				("Actra Work Permit Paid By - Production company", Boolean.class),
	PERMIT_OTHER_PAID_BY					("Actra Work Permit Paid By - Other", Boolean.class),
	PERMIT_VISA_PAYMENT_METHOD				("Actra Work Permit Payment Method - Visa", Boolean.class),
	PERMIT_MASTER_CARD_PAYMENT_METHOD		("Actra Work Permit Payment Method - Mastercard", Boolean.class),
//	PERMIT_INTERAC_PAYMENT_METHOD			("Actra Work Permit Payment Method - Interac", String.class),
	PERMIT_DEDUCT_SOURCE_PAYMENT_METHOD		("Actra Work Permit Payment Method - Deduct at source", Boolean.class),
	PERMIT_CHEQUE_PAYMENT_METHOD			("Actra Work Permit Payment Method - cheque", Boolean.class),
	PERMIT_CASH_PAYMENT_METHOD				("Actra Work Permit Payment Method - cash", Boolean.class),
	PERMIT_EMAIL_RECEIPT					("Actra Work Permit Receipt By Email", Boolean.class),
	PERMIT_MAIL_RECEIPT						("Actra Work Permit Receipt By Email", Boolean.class),
	PERMIT_ADDRESS_MAIL_RECEIPT				("Actra Work Permit Receipt To", String.class),
	PERMIT_CC_HOLDER_NAME					("Actra Work Permit Cc Holder Name", String.class),
	PERMIT_CC_HOLDER_SIGN_ID				("Actra Work Permit Cc Holder Sign Id", Integer.class),
	PERMIT_CC_NUM							("Actra Work Permit Cc Num", String.class),
	PERMIT_CC_EXPIRATION_DATE				("Actra Work Permit Cc Expiration Date", Date.class),
	PERMIT_ENGAGER_ID						("Actra Work Permit Engager Id", String.class),
	PERMIT_COM_ID							("Actra Work Permit Com Id", String.class),
	PERMIT_APPROVED_DATE					("Actra Work Permit Date Approved", Date.class),
	PERMIT_PROCESSED_DATE					("Actra Work Permit Date Processed", Date.class),
	PERMIT_APPROVED_DENIED_BY_SIGN_ID		("Actra Work Permit Approved Denied By", String.class),
	PERMIT_YES_QUALIFYING					("Actra Work Permit Qualifying - yes", Boolean.class),
	PERMIT_NO_QUALIFYING					("Actra Work Permit Qualifying - no", Boolean.class),
	PERMIT_WORK_PERMIT_NUM					("Actra Work Permit WorkPermit Num", String.class),
	PERMIT_DENIAL_REASON					("Actra Work Permit Denial Reason", String.class),

	// ACTRA Intent To Produce
	INTENT_ADVERTISER						("Actra Intent Advertiser", String.class),
	INTENT_PRODUCT  						("Actra Intent product", String.class),
	INTENT_AGENCY_NAME  					("Actra Intent Agency Name", String.class),
	INTENT_PRODUCER_NAME					("Actra Intent Producer Name", String.class),
	INTENT_SIGNATORY_ENGAGER 				("Actra Intent Signatory Engager", String.class),
	INTENT_DIRECTOR_NAME					("Actra Intent Director Name", String.class),
	INTENT_PRODUCTION_HOUSE_NAME  			("Actra Intent Production House Name", String.class),
	INTENT_LINE_PRODUCER_NAME  				("Actra Intent Line Producer Name", String.class),
	INTENT_CASTING_DIRECTOR_NAME  			("Actra Intent Casting Director Name", String.class),
	INTENT_MULTI_BRANCH  					("Actra Intent multi Branch", Boolean.class),
	INTENT_MULTI_BRANCH_LOCATIONS  			("Actra Intent multi Branch Locations", String.class),
	INTENT_USE_CANADA  						("Actra Intent use Canada", Boolean.class),
	INTENT_USE_US  							("Actra Intent Use Us", Boolean.class),
	INTENT_DIGITAL_MEDIA1  					("Actra Intent Digital Media 1", Boolean.class),
	INTENT_DIGITAL_MEDIA2  					("Actra Intent Digital Media 2", Boolean.class),
	INTENT_OTHER1  							("Actra Intent Other 1", Boolean.class),
	INTENT_OTHER2  							("Actra Intent Other 2", Boolean.class),
	INTENT_NATIONAL_COM  					("Actra Intent National Com", Boolean.class),
	INTENT_TV  								("Actra Intent Tv", Boolean.class),
	INTENT_RADIO  							("Actra Intent Radio", Boolean.class),
	INTENT_PSA  							("Actra Intent PSA", Boolean.class),
	INTENT_LOC_REGIONCOM  					("Actra Intent Loc Region Com", Boolean.class),
	INTENT_DOUBLE_SHOOT  					("Actra Intent DoubleS hoot", Boolean.class),
	INTENT_DEMO  							("Actra Intent Demo", Boolean.class),
	INTENT_A706EXCLUSIONS  					("Actra Intent A706 Exclusions", Boolean.class),
	INTENT_SEASONAL_COM  					("Actra Intent Seasonal Com", Boolean.class),
	INTENT_TAGS  							("Actra Intent Tags", Boolean.class),
	INTENT_DEALER  							("Actra Intent Dealer", Boolean.class),
	INTENT_INFORMERCIAL  					("Actra Intent informercial", Boolean.class),
	INTENT_SHORT_LIFE_7DAYS  				("Actra Intent Short Life 7 Days", Boolean.class),
	INTENT_SHORT_LIFE_14DAYS  				("Actra Intent Short Life 14 Days", Boolean.class),
	INTENT_SHORT_LIFE_31DAYS  				("Actra Intent Short Life 31 Days", Boolean.class),
	INTENT_SHORT_LIFE_45DAYS  				("Actra Intent Short Life 45 Days", Boolean.class),
	INTENT_COMMERCIAL_ID  					("Actra Intent Commercial Id", Integer.class),
	INTENT_MINOR 							("Actra Intent Minor", Boolean.class),
	INTENT_NUM_MINORS  						("Actra Intent Num Minors", Integer.class),
	INTENT_MINOR_AGES  						("Actra Intent Minor Ages", String.class),
	INTENT_NUM_EXTRAS_GENERAL  				("Actra Intent Num Extras General", Integer.class),
	INTENT_NUM_EXTRAS_GROUP  				("Actra Intent Num Extras Group", Integer.class),
	INTENT_NUM_EXTRAS_GROUP31  				("Actra Intent Num Extras Group 31", Integer.class),
	INTENT_STUNTS  							("Actra Intent Stunts", Boolean.class),
	INTENT_STUNT_TYPE  						("Actra Intent Stunt Type", String.class),
	INTENT_EXT_SCENES  						("Actra Intent Ext Scenes", Boolean.class),
	INTENT_EXT_SCENES_TYPE  				("Actra Intent Ext Scenes Type", String.class),
	INTENT_LOCATION_SHOOT_40RADIUS  		("Actra Intent Location Shoot 40 Radius", Boolean.class),
	INTENT_WEATHER_PERMITTING  				("Actra Intent Weather Permitting", Boolean.class),
	INTENT_WEEKEND_NIGHT  					("Actra Intent Weekend Night", Boolean.class),
	INTENT_NUDE_SCENES  					("Actra Intent Nude Scenes", Boolean.class),

	// Shared and Custom Form field types

	ACCOUNT_NUMBER					("Account Number", String.class),
	BENEFIT_YEAR_END				("End of Benefit Year", Date.class),
	BENEFIT_YEAR_START				("Start of Benefit Year",  Date.class),
	DEPARTMENT						("Department", String.class),
	EMERGENCY_CONTACT				("Emergency Contact Name", String.class),
	EMERGENCY_PHONE					("Emergency Phone", String.class),
	EMERGENCY_RELATION				("Emergency Relationship", String.class),
	EMPLOYEE_NAME					("Employee Name", String.class),
	PRODUCTION_COMPANY				("Production Company", String.class),
	PRODUCTION_TITLE				("Production Title", String.class),
	EMPLOYER_ADDRESS_COMPLETE		("Employer Full Address", String.class),
	DAYS_PER_WEEK					("Days per week", String.class),
	HOURS_PER_DAY					("Hours per day guaranteed", BigDecimal.class),
	HOURS_PER_WEEKLY_DAY			("Hours per weekly day", BigDecimal.class),
	HOURS_PER_WEEK_STUDIO			("Hours per week - studio", BigDecimal.class),  // LS-2757
	HOURS_PER_WEEK_DISTANT			("Hours per week - distant", BigDecimal.class), // LS-2757

	// UDA-INM (Canadian contract)
	INM_NUMBER						("INM number", String.class),
	PROD_NUMBER						("Production Number", String.class),
	PRODUCER_NAME					("Producer Name", String.class),
	PRODUCER_ADDRESS_1				("Producer Address", String.class),
	PRODUCER_ADDRESS_2				("Producer Address 1", String.class),
	PRODUCER_PHONE					("Producer Phone", String.class),
	PRODUCER_EMAIL					("Producer Email", String.class),
	RESPONSIBLE_NAME				("Responsible Name", String.class),
	PRODUCER_UDA					("Producer Uda", String.class),
	ARTIST_NAME						("Artist Name", String.class),
	COMPANY_NAME					("Company Name", String.class),
	ARTIST_ADDRESS_1				("Artist Address", String.class),
	ARTIST_ADDRESS_2				("Artist Address 1", String.class),
	ARTIST_PHONE					("Artist Phone", String.class),
	ARTIST_EMAIL					("Artist Email", String.class),
	ADVERTISER_NAME_1				("Advertiser Name", String.class),
	ADVERTISER_NAME_2				("Advertiser Name", String.class),
	ADVERTISER_NAME_3				("Advertiser Name", String.class),
	PRODUCT_NAME_1					("Product Name", String.class),
	PRODUCT_NAME_2					("Product Name", String.class),
	PRODUCT_NAME_3					("Product Name", String.class),
	ARTIST_GST						("Artist Gst", String.class),
	ARTIST_QST						("Artist Qst", String.class),
	SOCIAL_INSURANCE				("Social Insurance", String.class),
	NO_UDA_MEMBER					("No Uda Member", String.class),
	DATE_OF_BIRTH					("Date of Birth", String.class),
	MEMBER					        ("Member", BigDecimal.class),
	LESS_THAN_18YEARS				("Less Than 18 Year", Boolean.class),
	COMMERCIAL_TITLE				("Commercial Title", String.class),
	COMMERCIAL_VERSION				("Commercial Version", String.class),
	RECORDING1						("Recording 1", BigDecimal.class),
	RECORDING2						("Recording 2", BigDecimal.class),
	RECORDING3						("Recording 3", BigDecimal.class),
	RECORDING_OTHER					("Recording Other", BigDecimal.class),
	USE_TABLE_A						("User Table A", BigDecimal.class),
	USE_TABLE_B						("User Table B", BigDecimal.class),
	USE_TABLE_C						("User Table C", BigDecimal.class),
	USE_TABLE_D						("User Table D", BigDecimal.class),
	USE_TABLE_E						("User Table E", BigDecimal.class),
	USE_TABLE_F						("User Table F", BigDecimal.class),
	PERIOD          				("Period", Boolean.class),
	FIRST_USE_DATE					("First Use Date", BigDecimal.class),
	PROTFOLIO_USE_AUTHORIZATION		("Portfolio Use Authorization", BigDecimal.class),
	EXCLUSIVITY_DURATION			("Exclusive Duration", BigDecimal.class),
	EXCLUSIVITY_DUR_TEXT			("Exclusive Duration Text", BigDecimal.class),
	EXCLUSIVITY_SERVICE				("Exclusive Service", BigDecimal.class),
	FUNCTION_PRINCIPAL				("Function-Principal Performer", Boolean.class),
	FUNCTION_PRINCIPAL_EXTRA		("Function-Principal Extra", Boolean.class),
	FUNCTION_EXTRA					("Function-Extra", Boolean.class),
	FUNCTION_SOC					("Function-SOC Performer", Boolean.class),
	FUNCTION_VOICE_OVER				("Function-Voice Over", Boolean.class),
	FUNCTION_CHORIST				("Function-Chorist", Boolean.class),
	FUNCTION_DEMONSTRATOR			("Function-Demonstrator", Boolean.class),
	FUNCTION_OTHER	 				("Function-Other", Boolean.class),
	FUNCTION_OTR_TEXT				("Function Other Text", String.class),
	FEE_RATE						("Fee Rate", BigDecimal.class),
	NEGOTIABLE_RECORDING_PERCENT	("Negotiable recoring Percent", BigDecimal.class),
	NEGOTIABLE_INM_USE_AMOUNT		("Negotiable Inm Use Amount", BigDecimal.class),
	NEGOTIABLE_RECORDING_AMOUNT		("Negotiable Recording Amount", BigDecimal.class),
	SPECIAL_CONDITION_2				("Special Condition 2", BigDecimal.class),
	NEGOTIABLE_OTHER_PERCENT		("Negotiable Other Percent", BigDecimal.class),
	NEGOTIABLE_OTHER_AMOUNT			("Negotiable Ohter Amount", BigDecimal.class),
	SPECIAL_CONDITION_3				("Special Condition 3", BigDecimal.class),
	NEGOTIABLE_DATE_A				("Negotiable Date A", Date.class),
	NEGOTIABLE_DATE_B				("Negotiable Date B", Date.class),
	FUNCTION_RATE					("Function Rate", BigDecimal.class),
	FUNCTION_NAME					("Function Name", BigDecimal.class),
	ADDITIONAL_AMOUNT				("Regular Rate", BigDecimal.class),
	OT_HOUR_NUMBER					("Ot Hours", BigDecimal.class),
	OT_HOUR_AMOUNT					("Ot Hour Amount", BigDecimal.class),
	OT_HOUR_TOTAL					("Ot Hour Total", BigDecimal.class),
	ADD_OT_HRS_NUMBER				("Add Ot Hours", BigDecimal.class),
	ADD_OT_HRS_AMOUNT				("Add Ot Hour Amount", BigDecimal.class),
	ADD_OT_HRS_TOTAL				("Add Ot Hour Total", BigDecimal.class),
	NIGHT_HOUR_NUMBER				("Night Hours", BigDecimal.class),
	NIGHT_HOUR_AMOUNT				("Night Hour Amount", BigDecimal.class),
	NIGHT_HOUR_TOTAL				("Night Hour Total", BigDecimal.class),
	OT_NIGHT_HRS_NUMBER			    ("Ot Night Hours", BigDecimal.class),
	OT_NIGHT_HRS_AMOUNT			    ("Ot Night Hour Amount", BigDecimal.class),
	OT_NIGHT_HRS_TOTAL				("Ot Night Hour Total", BigDecimal.class),
	HOLIDAY_HOUR_NUMBER				("Holiday Hours", BigDecimal.class),
	HOLIDAY_HOUR_AMOUNT				("Holiday Hour Amount", BigDecimal.class),
	HOLIDAY_HOUR_TOTAL				("Holiday Hour Total", String.class),
	TRAVEL_HOUR_NUMBER				("Travel Hours", BigDecimal.class),
	TRAVEL_HOUR_AMOUNT				("Travel Hour Amount", BigDecimal.class),
	TRAVEL_HOUR_TOTAL				("Travel Hour Total", BigDecimal.class),
	WAITING_HOUR_NUMBER				("Waiting Hours", BigDecimal.class),
	WAITING_HOUR_AMOUNT				("Waiting Hour Amount", BigDecimal.class),
	WAITING_HOUR_TOTAL				("Waiting Hour Total", BigDecimal.class),
	STAND_BY_DAY_NUMBER				("Stand By Days", BigDecimal.class),
	STAND_BY_DAY_AMOUNT				("Stand By Day Amount", BigDecimal.class),
	STAND_BY_DAY_TOTAL				("Stand By Day Total", BigDecimal.class),
	LODGING_MEALS_NUMBER			("Lodging Meals", BigDecimal.class),
	LODGING_MEALS_AMOUNT			("Lodging Meal Amount", BigDecimal.class),
	LODGING_MEALS_TOTAL				("Lodging Meal Total", BigDecimal.class),
	MEAL_CHOICE						("Meals Only", BigDecimal.class),
	MEAL_ONLY_NUMBER				("Meals Only Number", BigDecimal.class),
	MEAL_ONLY_AMOUNT				("Meals Only Amount", BigDecimal.class),
	MEAL_ONLY_TOTAL					("Meals Only Total", BigDecimal.class),
	FITTING_REHEARSAL_NUMBER		("Fitting Rehearsals", BigDecimal.class),
	FITTING_REHEARSAL_AMOUNT		("Fitting Rehearsal Amount", BigDecimal.class),
	FITTING_REHEARSAL_TOTAL			("Fitting Rehearsal Total", BigDecimal.class),
	MILEAGE_RATE_NUMBER				("Mileage Rate", BigDecimal.class),
	MILEAGE_RATE_AMOUNT				("Mileage Rate Amount", BigDecimal.class),
	MILEAGE_RATE_TOTAL				("Mileage Rate Amount Total", BigDecimal.class),
	CALL_BACK_ON_CAMERA_NUMBER		("Call back On Camera", BigDecimal.class),
	CALL_BACK_ON_CAMERA_TOTAL		("Call back On Camera Total", BigDecimal.class),
	CALL_BACK_OFF_CAMERA_NUMBER		("Call back Off Camera", BigDecimal.class),
	CALL_BACK_OFF_CAMERA_TOTAL		("Call back Off Camera Total", BigDecimal.class),
	TAG_NUMBER						("Tag Number", BigDecimal.class),
	TAG_VALUE                       ("Tag Value", BigDecimal.class),
	TAG_TOTAL						("Tag Total", BigDecimal.class),
	OTHERS_NUMBER					("Others", BigDecimal.class),
	OTHERS_TOTAL					("Others Total", BigDecimal.class),
	GROSS_FEE						("Gross Fee", BigDecimal.class),
	APPRENTICE						("Apprentice", BigDecimal.class),
	PERMIT_HOLDR_NUMBER			    ("Permit Holder Number", BigDecimal.class),
	PERMIT_NUMBER					("Permit Number", BigDecimal.class),
	PERMITS_TOTAL					("Permit Total", BigDecimal.class),
	PERMIT_AMOUNT					("Permit Amount", BigDecimal.class),
	MINORITY_AGED_ARTISTS_FUND		("Minority Aged Artist Fund", BigDecimal.class),
	FEE_BEFORE_TAXES				("Fee Before Taxes", BigDecimal.class),
	GST_NUMBER						("Gst", BigDecimal.class),
	QST_NUMBER						("Qst", BigDecimal.class),
	NET_FEE							("Net Fee", BigDecimal.class),
	PRODUCER_SHARE					("Producer Share", BigDecimal.class),
	TOTAL_AMOUNT_TO_CSA				("Total Amount To Csa", BigDecimal.class),
	COMMERCIAL_DESCRIPTION			("Commercial Description", String.class),
	NEGOTIABLE_INM_USE_PERCENT		("Inm Use Percent", String.class),
	SPECIAL_CONDITION_1				("Special Condition 1", String.class),
	SIGNATURE_DATE					("Special Condition 1", String.class),
	EMPLOYEE_SIGN_NAME_2		    ("Signature", String.class),
	EMP_SIGN_NAME_2                 ("Signature", String.class),
	FUNC_LODGING_MEALS              ("Function lodging meal only", Boolean.class),
	FUNC_MEAL_ONLY                  ("Function meal only", Boolean.class),

	// Model Release form
	MR_TTC_CLIENT                     ("TTC Client", String.class),
	MR_MODEL_NAME                     ("Model Name", String.class),
	MR_MODEL_SSN                      ("Model Ssn", String.class),
	MR_MODEL_AGENCY_YES               ("Model Agency", Boolean.class),
	MR_MODEL_AGENCY_TEXT              ("Model Agency Text", String.class),
	MR_MODEL_AGENCY_NO                ("Model Agency Number", String.class),
	MR_MODEL_CORPORATION_YES          ("Model Agency Corporation Yes", String.class),
	MR_MODEL_CORPORATION_TEXT         ("Model Agency Corporation Text", String.class),
	MR_MODEL_CORPORATION_NO           ("Model Agency Corporation Number", String.class),
	MR_MODEL_CORPORATION_FEDERAL      ("Model Agency Corporation Federal", String.class),
	MR_CORPORATION_FEDERAL_ID	      ("Model Corporation Federal Id", String.class),
	MR_CORPORATION_FEDERAL_NO         ("Model Corporation Federal No", String.class),
	MR_PRJECT_NAME                    ("Model Project Name", String.class),
	MR_JOB                            ("Model Job", String.class),
	MR_JB_PO                          ("Model Job PO", String.class),
	MR_SHOOT_DATES                    ("Model Shoot Dates", String.class),
	MR_PRODUCT                        ("Model Product", String.class),
	MR_ADVERTISER                     ("Model Advertiser", String.class),
	MR_AD_AGENCY                      ("Model Ad Agency", String.class),
	MR_PRODUCER_NAME                  ("Model Producer Name", String.class),
	MR_PHOTOGRAPHER                   ("Model Photographer", String.class),
	MR_JB_LOCATION                    ("Model Job Location", String.class),
	MR_USGE_YES                       ("Usage Yes", String.class),
	MR_USGE_NO                        ("Usage No", String.class),
	MR_UNLIMITED                      ("Unlimited", String.class),
	MR_UNLMTD_EXCEPT_OUTDOOR          ("Unlimited Except Outdoor", String.class),
	MR_ELECTRIC_MEDIA                 ("Electric Media", String.class),
	MR_BROLL                          ("Broll", String.class),
	MR_DIRECT_MAIL                    ("Direct Mail", String.class),
	MR_COLLATERAL                     ("Collateral", String.class),
	MR_ISM                            ("Ism", String.class),
	MR_PR_DATA                        ("Pr data", String.class),
	MR_PRINT                          ("Print", String.class),
	MR_CIRCULAR                       ("Circular", String.class),
	MR_INDUSTRIAL                     ("Industrail", String.class),
	MR_MEDIA_OTHER                    ("Media Other", String.class),
	MR_MEDIA_OTR_TEXT                 ("Media Other Text", String.class),
	MR_TERM                           ("Term", String.class),
	MR_TRM_MONTH                      ("Term Month", String.class),
	MR_TRM_DATE                       ("Term Date", String.class),
	MR_TRM_YEAR                       ("Term Year", String.class),
	MR_UNLMTD_TIME                    ("Unlimited Time", String.class),
	MR_TRM_OHER                       ("Term Other", String.class),
	MR_NORTH_AMERICA                  ("North America", String.class),
	MR_EUROPEAN_UNION                 ("European Union", String.class),
	MR_SOUTH_AMERICA                  ("South America", String.class),
	MR_ASIA                           ("Asia", String.class),
	MR_WORLD_WIDE                     ("World Wide", String.class),
	MR_WRLD_WIDE_ELECTRONIC_MEDIA     ("World Wide Electronic Media", String.class),
	MR_TERRITORY_OTHER                ("Territory", String.class),
	MR_TERRITRY_OTHER_TEXT            ("Territory Other Text", String.class),
	MR_OPTIONAL_REUSE_YES             ("Optional Reuse Yes", String.class),
	MR_OPTIONAL_REUSE_NO              ("Optional Reuse No", String.class),
	MR_REUSE_MEDIA                    ("Reuse media", String.class),
	MR_REUSE_TERM                     ("Reuse Term", String.class),
	MR_REUSE_TERRITORY                ("Reuse Territory",String.class),
	MR_REUSE_FEE                      ("Reuse Fee", String.class),
	MR_COMPENSATION_YES               ("Compensation Yes", String.class),
	MR_COMPENSATION_NO                ("Compensation No", String.class),
	MR_RATE_FOR_SERVICE               ("Rate for Service", String.class),
	MR_PER_DAY                        ("Per Day", String.class),
	MR_PER_HOUR                       ("Per Hour", String.class),
	MR_SERVICE_HOURS                  ("Service Hours", String.class),
	MR_RIGHT_TERM                     ("Right Term", String.class),
	MR_NOT_RIGHT_TERM                 ("Not Right Term", String.class),
	MR_USAGE                          ("Usage", String.class),
	MR_ADDL_YES                       ("Additional Yes", String.class),
	MR_ADDL_NO                        ("Additional No", String.class),
	MR_ADDL_OVER_TIME                 ("Additional Over Time", String.class),
	MR_ADDL_PER_HOUR                  ("Additional Per Hours", String.class),
	MR_ADDL_HOURS                     ("Additional Hours", String.class),
	MR_SHOOT_DAY                      ("Shoot Day", String.class),
	MR_SHOOT_PER_DAY                  ("Shoot Per Day", String.class),
	MR_SHOOT_PER_HOURS                ("Shoot Per Hours", String.class),
	MR_PREP_DAY                       ("Prep Day", String.class),
	MR_PREP_PER_DAY                   ("Prep Per Day", String.class),
	MR_PREP_PER_HOURS                 ("Prep Per Hours", String.class),
	MR_WEATHER_DAY                    ("Weather Day", String.class),
	MR_WEATHER_PER_DAY                ("Weather Per Day", String.class),
	MR_WEATHER_HOURS                  ("Weather Hours", String.class),
	MR_INITIMATES_DAY                 ("Intimate Day", String.class),
	MR_INITIMATE_PER_DAY              ("Intimate Per Day", String.class),
	MR_INTIMATE_PER_HOURS             ("Intimate Per Hours", String.class),
	MR_TRAVEL_DAY_RATE                ("Travel Day Rate", String.class),
	MR_TRAVEL_DAY_PER_DAY             ("Travel Day Per Day", String.class),
	MR_TRAVEL_DAY_PER_HOURS	          ("Travel Day Per Hours", String.class),
	MR_NON_TAXABLE                    ("Non Taxable", String.class),
	MR_TAXABLE                        ("Taxable", String.class),
	MR_ADDITIONAL_PROVISIONS          ("Additional Provisions", String.class),
	MR_PROJECT                        ("Project", String.class),
	MR_JB_MODEL                       ("Job Model", String.class),
	MR_AGE                            ("Age", String.class),
	MR_UNDER_AGE                      ("Under Age", String.class),
	MR_GUIDANCE                       ("Guidance", String.class),
	MR_MDEL                           ("Model", String.class),
	MR_MODEL_AGNCY                    ("Model Agency", String.class),
	MR_PRODCER                        ("Producer", String.class),
	MR_GUARDIAN                       ("Guardian", String.class),
	MR_MODEL_PRINT_NAME               ("Model Print Name", String.class),
	MR_PRODUCER_PRINT_NAME            ("Producer Print Name", String.class),
	MR_MODEL_DATE                     ("Model Date", String.class),
	MR_PRODUCER_DATE                  ("Producer Date", String.class),
	MR_COMPANY                        ("Company", String.class),
	MR_MODEL_EMAIL                    ("Model Email", String.class),
	MR_PRODUCER_EMAIL                 ("Producer Email", String.class),
	MR_MODEL_PHONE                    ("Model Phone", String.class),
	MR_PRODUCER_PHONE                 ("Producer Phone", String.class),
	MR_MODEL_AGENCY_NAME              ("Model Agency Name", String.class),
	MR_MODEL_AGENCY_STREET            ("Model Agency Street", String.class),
	MR_MODEL_AGENCY_PHONE             ("Model Agency Phone", String.class),
	MR_MODEL_AGENCY_COMPANY           ("Model Agency company", String.class),
	MR_MODEL_ADDRESS                  ("Model Address", String.class),
	MR_PRODUCER_ADDRESS               ("Model Producer Address", String.class),
	MR_PRODUCER_COMPANY               ("Producer Company", String.class),
	MR_ACKNOWLEDGED                   ("Acknowledged", String.class),
	// LS-3223 New fields for pdf.
	MR_NON_TAXABLE_TOTAL              ("Reimbursement Non-Taxable Total Amount", BigDecimal.class),
	MR_TAX_TOTAL                      ("Reimbursement Taxable Total Amount", BigDecimal.class),
	MR_MEALS_INCIDENTALS              ("Per Diem Meals and Incidentals", Boolean.class),
	MR_LODGING		                  ("Per Diem Lodging", Boolean.class),
	MR_PER_DIEM_RATE                  ("Per Diem Rate", BigDecimal.class),
	MR_PER_DIEM_DAYS                  ("Number of days Per Diem will be paid", Integer.class),
	MR_TRM_OHR_TEXT                   ("Term Text", String.class),
	MR_AGENT_PERCENTAGE               ("Agent Percentage", String.class),
	MR_SHOOTUSE                       ("Shoot Use", Boolean.class), 
	MR_USEONLY                        ("Use Only", Boolean.class),
	MR_OCCUPATION                     ("Occupation", String.class),
	N_A                               ("NA", String.class),
	;

	/** A description of the field; this may be used in the detailed Audit trail when displaying
	 * a  {@link com.lightspeedeps.object.RuleFilter RuleFilter} applied as part of a
	 * {@link com.lightspeedeps.model.ContractRule ContractRule}. */
	private final String description;

	/** The expected class of a value to which this field will be compared. The currently used
	 * values are Integer, BigDecimal, and String. */
	@SuppressWarnings("rawtypes")
	private final Class clazz;

	/**
	 * The only constructor.
	 *
	 * @param clas See {@link #clazz}
	 * @param desc See {@link #description}
	 */
	@SuppressWarnings("rawtypes")
	FormFieldType(String desc, Class clas) {
		description = desc;
		clazz = clas;
	}

	/**See {@link #clazz}. */
	@SuppressWarnings("rawtypes")
	public Class getClazz() {
		return clazz;
	}

	/**
	 * Returns a "pretty" mixed-case version of the enumerated value.
	 * <p>
	 * NOTE: This overrides the default toString(), which returns
	 * the same value as name(), which is the exact text of the enum name.
	 */
	@Override
	public String toString() {
		return description;
	}

	/**
	 * Returns the "pretty" printable version of this enumerated type. It is the same as toString,
	 * but can be used from jsp pages since it follows the bean accessor (getter) naming convention.
	 * This could be enhanced to use the current locale setting for i18n purposes.
	 *
	 * @return The value of the enumerated type as mixed-case text.
	 */
	public String getLabel() {
		return toString();
	}

}
