/**
 * File: NotificationType.java
 */
package com.lightspeedeps.type;

/**
 * The types of Notifications that can be generated.
 */
public enum NotificationType {
	ACCOUNT_DELETED,
	ALLOCATION_SENT,
	CALL_TIME_PUBLISHED,
	CALL_TIME_CHANGED,
	CALL_TIME_REMOVED,
	CALL_TIME_ADDED,
	DAY_TYPE_CHANGED,
	DIRECTIONS,
	DOCUMENT_DISTRIBUTED,
	DOCUMENT_PULLED,
	//DOCUMENT_READY,
	DOCUMENT_RECALLED,
	DOCUMENT_REJECTED,
	DOCUMENT_VOIDED,
	DOCUMENTS_SENT,
	DPR,
	//FORM_I9_EXPIRED,
	//FORM_I9_SUBMITTED,
	FORM_I9_WAITING,
	LOCATION_CHANGED,
	NEW_ACCOUNT,
	NEW_CONTACT,
	NEW_CONTACT_ACCEPT,
	NEW_CONTACT_DECLINE,
	PRODUCTION_CREATED,
	PRODUCTION_UNSUBSCRIBED,
	PRODUCTION_RESUBSCRIBED,
	PRODUCTION_UPGRADED,
	PROJECT_SENT,
	PW_RESET,
	REPORT_DUE,
	REPORT_OVERDUE,
	REPORT_PUBLISHED,
	REPORT_SUBMITTED,
	SCENE_CHANGED,
	SCRIPT_PAGES,
	STRIPBOARD_CHANGED,
	TIMECARD_BATCH_SENT,
	TIMECARD_PULLED,
	TIMECARD_READY,
	TIMECARD_RECALLED,
	TIMECARD_REJECTED,
	TIMECARD_SUBMITTED,
	TIMECARD_VOIDED,
	TIMESHEET_SENT,
	TIMESHEET_SUBMITTED,
	USER_LOCK_OUT,
	WELCOME;
}
