//	File Name:	ReportType.java
package com.lightspeedeps.type;

/**
 * An enumeration used in the ReportRequirement and ReportRequest classes. It describes
 * a type of report generated by the application.
 */
public enum ReportType {
	CALL_SHEET			("Complete Call Sheets",		"callsheet",		true),
	DPR					("Complete Production Reports",	"dpr",				false),
	EXHIBIT_G			("Complete SAG Exhibit G",		"exhibit_g",		false),
	TIME_SHEET			("Complete Timesheets",			"timesheet",		false),
	TAFT_HARTLEY		("Complete Taft-Hartley",		"taft_hartley",		false),
	EXTRAS				("Complete Extras",				"extras",			false),
	APPROVE_DPR			("Approve Production Reports",	"approveDpr",		false),
//	APPROVE_TIMESHEET	("Approve Timesheets",			"approveTimesheet",	false)
	PROJECT				("Project", 					"project", 			false),
	TIMECARD			("Timecard", 					"timecard", 		false),
	START_DOCUMENT		("Start Document",				"startDoc", 		false),
	;

	/** The descriptive name to display (e.g., in a drop-down list) for this ReportType entry. */
	private final String heading;

	/** The text used for substituting into the message resource file
	 * property name, for extracting message text related to a given report. */
	private final String message;

	/** True iff reports of this ReportType are unique to a particular Unit. */
	private final boolean forUnit;

	ReportType(String head, String msg, boolean b) {
		heading = head;
		message = msg;
		forUnit = b;
	}

	/** Returns the "pretty" printable version of this enumerated type.
	 * <p>
	 * See {@link #heading}. */
	@Override
	public String toString() {
		return heading;
	}

	/**
	 * Returns the "pretty" printable version of this enumerated type. It is the same as toString,
	 * but can be used from jsp pages since it follows the bean accessor (getter) naming convention.
	 * This could be enhanced to use the current locale setting for i18n purposes.
	 *
	 * @return The value of the enumerated type as mixed-case text.
	 */
	public String getLabel() {
		return toString();
	}

	/**
	 * Returns the string used for substituting into the message resource file
	 * property name, for extracting message text related to a given report.
	 */
	public String getMessageName() {
		return message;
	}

	/** See {@link #forUnit}. */
	public boolean isForUnit() {
		return forUnit;
	}

}
